// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newAttrValue(db *gorm.DB, opts ...gen.DOOption) attrValue {
	_attrValue := attrValue{}

	_attrValue.attrValueDo.UseDB(db, opts...)
	_attrValue.attrValueDo.UseModel(&model.AttrValue{})

	tableName := _attrValue.attrValueDo.TableName()
	_attrValue.ALL = field.NewAsterisk(tableName)
	_attrValue.AttrValueID = field.NewInt64(tableName, "attr_value_id")
	_attrValue.ValueName = field.NewString(tableName, "value_name")
	_attrValue.AttrID = field.NewInt64(tableName, "attr_id")
	_attrValue.CreateTime = field.NewTime(tableName, "create_time")
	_attrValue.UpdateTime = field.NewTime(tableName, "update_time")

	_attrValue.fillFieldMap()

	return _attrValue
}

type attrValue struct {
	attrValueDo

	ALL         field.Asterisk
	AttrValueID field.Int64
	ValueName   field.String
	AttrID      field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (a attrValue) Table(newTableName string) *attrValue {
	a.attrValueDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a attrValue) As(alias string) *attrValue {
	a.attrValueDo.DO = *(a.attrValueDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *attrValue) updateTableName(table string) *attrValue {
	a.ALL = field.NewAsterisk(table)
	a.AttrValueID = field.NewInt64(table, "attr_value_id")
	a.ValueName = field.NewString(table, "value_name")
	a.AttrID = field.NewInt64(table, "attr_id")
	a.CreateTime = field.NewTime(table, "create_time")
	a.UpdateTime = field.NewTime(table, "update_time")

	a.fillFieldMap()

	return a
}

func (a *attrValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *attrValue) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["attr_value_id"] = a.AttrValueID
	a.fieldMap["value_name"] = a.ValueName
	a.fieldMap["attr_id"] = a.AttrID
	a.fieldMap["create_time"] = a.CreateTime
	a.fieldMap["update_time"] = a.UpdateTime
}

func (a attrValue) clone(db *gorm.DB) attrValue {
	a.attrValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a attrValue) replaceDB(db *gorm.DB) attrValue {
	a.attrValueDo.ReplaceDB(db)
	return a
}

type attrValueDo struct{ gen.DO }

type IAttrValueDo interface {
	gen.SubQuery
	Debug() IAttrValueDo
	WithContext(ctx context.Context) IAttrValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAttrValueDo
	WriteDB() IAttrValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAttrValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAttrValueDo
	Not(conds ...gen.Condition) IAttrValueDo
	Or(conds ...gen.Condition) IAttrValueDo
	Select(conds ...field.Expr) IAttrValueDo
	Where(conds ...gen.Condition) IAttrValueDo
	Order(conds ...field.Expr) IAttrValueDo
	Distinct(cols ...field.Expr) IAttrValueDo
	Omit(cols ...field.Expr) IAttrValueDo
	Join(table schema.Tabler, on ...field.Expr) IAttrValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAttrValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAttrValueDo
	Group(cols ...field.Expr) IAttrValueDo
	Having(conds ...gen.Condition) IAttrValueDo
	Limit(limit int) IAttrValueDo
	Offset(offset int) IAttrValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAttrValueDo
	Unscoped() IAttrValueDo
	Create(values ...*model.AttrValue) error
	CreateInBatches(values []*model.AttrValue, batchSize int) error
	Save(values ...*model.AttrValue) error
	First() (*model.AttrValue, error)
	Take() (*model.AttrValue, error)
	Last() (*model.AttrValue, error)
	Find() ([]*model.AttrValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AttrValue, err error)
	FindInBatches(result *[]*model.AttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AttrValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAttrValueDo
	Assign(attrs ...field.AssignExpr) IAttrValueDo
	Joins(fields ...field.RelationField) IAttrValueDo
	Preload(fields ...field.RelationField) IAttrValueDo
	FirstOrInit() (*model.AttrValue, error)
	FirstOrCreate() (*model.AttrValue, error)
	FindByPage(offset int, limit int) (result []*model.AttrValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAttrValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a attrValueDo) Debug() IAttrValueDo {
	return a.withDO(a.DO.Debug())
}

func (a attrValueDo) WithContext(ctx context.Context) IAttrValueDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a attrValueDo) ReadDB() IAttrValueDo {
	return a.Clauses(dbresolver.Read)
}

func (a attrValueDo) WriteDB() IAttrValueDo {
	return a.Clauses(dbresolver.Write)
}

func (a attrValueDo) Session(config *gorm.Session) IAttrValueDo {
	return a.withDO(a.DO.Session(config))
}

func (a attrValueDo) Clauses(conds ...clause.Expression) IAttrValueDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a attrValueDo) Returning(value interface{}, columns ...string) IAttrValueDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a attrValueDo) Not(conds ...gen.Condition) IAttrValueDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a attrValueDo) Or(conds ...gen.Condition) IAttrValueDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a attrValueDo) Select(conds ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a attrValueDo) Where(conds ...gen.Condition) IAttrValueDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a attrValueDo) Order(conds ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a attrValueDo) Distinct(cols ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a attrValueDo) Omit(cols ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a attrValueDo) Join(table schema.Tabler, on ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a attrValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a attrValueDo) RightJoin(table schema.Tabler, on ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a attrValueDo) Group(cols ...field.Expr) IAttrValueDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a attrValueDo) Having(conds ...gen.Condition) IAttrValueDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a attrValueDo) Limit(limit int) IAttrValueDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a attrValueDo) Offset(offset int) IAttrValueDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a attrValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAttrValueDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a attrValueDo) Unscoped() IAttrValueDo {
	return a.withDO(a.DO.Unscoped())
}

func (a attrValueDo) Create(values ...*model.AttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a attrValueDo) CreateInBatches(values []*model.AttrValue, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a attrValueDo) Save(values ...*model.AttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a attrValueDo) First() (*model.AttrValue, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttrValue), nil
	}
}

func (a attrValueDo) Take() (*model.AttrValue, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttrValue), nil
	}
}

func (a attrValueDo) Last() (*model.AttrValue, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttrValue), nil
	}
}

func (a attrValueDo) Find() ([]*model.AttrValue, error) {
	result, err := a.DO.Find()
	return result.([]*model.AttrValue), err
}

func (a attrValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AttrValue, err error) {
	buf := make([]*model.AttrValue, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a attrValueDo) FindInBatches(result *[]*model.AttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a attrValueDo) Attrs(attrs ...field.AssignExpr) IAttrValueDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a attrValueDo) Assign(attrs ...field.AssignExpr) IAttrValueDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a attrValueDo) Joins(fields ...field.RelationField) IAttrValueDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a attrValueDo) Preload(fields ...field.RelationField) IAttrValueDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a attrValueDo) FirstOrInit() (*model.AttrValue, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttrValue), nil
	}
}

func (a attrValueDo) FirstOrCreate() (*model.AttrValue, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttrValue), nil
	}
}

func (a attrValueDo) FindByPage(offset int, limit int) (result []*model.AttrValue, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a attrValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a attrValueDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a attrValueDo) Delete(models ...*model.AttrValue) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *attrValueDo) withDO(do gen.Dao) *attrValueDo {
	a.DO = *do.(*gen.DO)
	return a
}
