// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newCategory1(db *gorm.DB, opts ...gen.DOOption) category1 {
	_category1 := category1{}

	_category1.category1Do.UseDB(db, opts...)
	_category1.category1Do.UseModel(&model.Category1{})

	tableName := _category1.category1Do.TableName()
	_category1.ALL = field.NewAsterisk(tableName)
	_category1.Category1ID = field.NewInt64(tableName, "category1_id")
	_category1.Name = field.NewString(tableName, "name")
	_category1.CreateTime = field.NewTime(tableName, "create_time")
	_category1.UpdateTime = field.NewTime(tableName, "update_time")

	_category1.fillFieldMap()

	return _category1
}

type category1 struct {
	category1Do

	ALL         field.Asterisk
	Category1ID field.Int64
	Name        field.String
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (c category1) Table(newTableName string) *category1 {
	c.category1Do.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c category1) As(alias string) *category1 {
	c.category1Do.DO = *(c.category1Do.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *category1) updateTableName(table string) *category1 {
	c.ALL = field.NewAsterisk(table)
	c.Category1ID = field.NewInt64(table, "category1_id")
	c.Name = field.NewString(table, "name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *category1) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *category1) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["category1_id"] = c.Category1ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c category1) clone(db *gorm.DB) category1 {
	c.category1Do.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c category1) replaceDB(db *gorm.DB) category1 {
	c.category1Do.ReplaceDB(db)
	return c
}

type category1Do struct{ gen.DO }

type ICategory1Do interface {
	gen.SubQuery
	Debug() ICategory1Do
	WithContext(ctx context.Context) ICategory1Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICategory1Do
	WriteDB() ICategory1Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICategory1Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICategory1Do
	Not(conds ...gen.Condition) ICategory1Do
	Or(conds ...gen.Condition) ICategory1Do
	Select(conds ...field.Expr) ICategory1Do
	Where(conds ...gen.Condition) ICategory1Do
	Order(conds ...field.Expr) ICategory1Do
	Distinct(cols ...field.Expr) ICategory1Do
	Omit(cols ...field.Expr) ICategory1Do
	Join(table schema.Tabler, on ...field.Expr) ICategory1Do
	LeftJoin(table schema.Tabler, on ...field.Expr) ICategory1Do
	RightJoin(table schema.Tabler, on ...field.Expr) ICategory1Do
	Group(cols ...field.Expr) ICategory1Do
	Having(conds ...gen.Condition) ICategory1Do
	Limit(limit int) ICategory1Do
	Offset(offset int) ICategory1Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICategory1Do
	Unscoped() ICategory1Do
	Create(values ...*model.Category1) error
	CreateInBatches(values []*model.Category1, batchSize int) error
	Save(values ...*model.Category1) error
	First() (*model.Category1, error)
	Take() (*model.Category1, error)
	Last() (*model.Category1, error)
	Find() ([]*model.Category1, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Category1, err error)
	FindInBatches(result *[]*model.Category1, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Category1) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICategory1Do
	Assign(attrs ...field.AssignExpr) ICategory1Do
	Joins(fields ...field.RelationField) ICategory1Do
	Preload(fields ...field.RelationField) ICategory1Do
	FirstOrInit() (*model.Category1, error)
	FirstOrCreate() (*model.Category1, error)
	FindByPage(offset int, limit int) (result []*model.Category1, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICategory1Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c category1Do) Debug() ICategory1Do {
	return c.withDO(c.DO.Debug())
}

func (c category1Do) WithContext(ctx context.Context) ICategory1Do {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c category1Do) ReadDB() ICategory1Do {
	return c.Clauses(dbresolver.Read)
}

func (c category1Do) WriteDB() ICategory1Do {
	return c.Clauses(dbresolver.Write)
}

func (c category1Do) Session(config *gorm.Session) ICategory1Do {
	return c.withDO(c.DO.Session(config))
}

func (c category1Do) Clauses(conds ...clause.Expression) ICategory1Do {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c category1Do) Returning(value interface{}, columns ...string) ICategory1Do {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c category1Do) Not(conds ...gen.Condition) ICategory1Do {
	return c.withDO(c.DO.Not(conds...))
}

func (c category1Do) Or(conds ...gen.Condition) ICategory1Do {
	return c.withDO(c.DO.Or(conds...))
}

func (c category1Do) Select(conds ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Select(conds...))
}

func (c category1Do) Where(conds ...gen.Condition) ICategory1Do {
	return c.withDO(c.DO.Where(conds...))
}

func (c category1Do) Order(conds ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Order(conds...))
}

func (c category1Do) Distinct(cols ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c category1Do) Omit(cols ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Omit(cols...))
}

func (c category1Do) Join(table schema.Tabler, on ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Join(table, on...))
}

func (c category1Do) LeftJoin(table schema.Tabler, on ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c category1Do) RightJoin(table schema.Tabler, on ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c category1Do) Group(cols ...field.Expr) ICategory1Do {
	return c.withDO(c.DO.Group(cols...))
}

func (c category1Do) Having(conds ...gen.Condition) ICategory1Do {
	return c.withDO(c.DO.Having(conds...))
}

func (c category1Do) Limit(limit int) ICategory1Do {
	return c.withDO(c.DO.Limit(limit))
}

func (c category1Do) Offset(offset int) ICategory1Do {
	return c.withDO(c.DO.Offset(offset))
}

func (c category1Do) Scopes(funcs ...func(gen.Dao) gen.Dao) ICategory1Do {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c category1Do) Unscoped() ICategory1Do {
	return c.withDO(c.DO.Unscoped())
}

func (c category1Do) Create(values ...*model.Category1) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c category1Do) CreateInBatches(values []*model.Category1, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c category1Do) Save(values ...*model.Category1) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c category1Do) First() (*model.Category1, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category1), nil
	}
}

func (c category1Do) Take() (*model.Category1, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category1), nil
	}
}

func (c category1Do) Last() (*model.Category1, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category1), nil
	}
}

func (c category1Do) Find() ([]*model.Category1, error) {
	result, err := c.DO.Find()
	return result.([]*model.Category1), err
}

func (c category1Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Category1, err error) {
	buf := make([]*model.Category1, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c category1Do) FindInBatches(result *[]*model.Category1, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c category1Do) Attrs(attrs ...field.AssignExpr) ICategory1Do {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c category1Do) Assign(attrs ...field.AssignExpr) ICategory1Do {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c category1Do) Joins(fields ...field.RelationField) ICategory1Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c category1Do) Preload(fields ...field.RelationField) ICategory1Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c category1Do) FirstOrInit() (*model.Category1, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category1), nil
	}
}

func (c category1Do) FirstOrCreate() (*model.Category1, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category1), nil
	}
}

func (c category1Do) FindByPage(offset int, limit int) (result []*model.Category1, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c category1Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c category1Do) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c category1Do) Delete(models ...*model.Category1) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *category1Do) withDO(do gen.Dao) *category1Do {
	c.DO = *do.(*gen.DO)
	return c
}
