// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newCategory2(db *gorm.DB, opts ...gen.DOOption) category2 {
	_category2 := category2{}

	_category2.category2Do.UseDB(db, opts...)
	_category2.category2Do.UseModel(&model.Category2{})

	tableName := _category2.category2Do.TableName()
	_category2.ALL = field.NewAsterisk(tableName)
	_category2.Category2ID = field.NewInt64(tableName, "category2_id")
	_category2.Name = field.NewString(tableName, "name")
	_category2.Category1ID = field.NewInt64(tableName, "category1_id")
	_category2.CreateTime = field.NewTime(tableName, "create_time")
	_category2.UpdateTime = field.NewTime(tableName, "update_time")

	_category2.fillFieldMap()

	return _category2
}

type category2 struct {
	category2Do

	ALL         field.Asterisk
	Category2ID field.Int64
	Name        field.String
	Category1ID field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (c category2) Table(newTableName string) *category2 {
	c.category2Do.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c category2) As(alias string) *category2 {
	c.category2Do.DO = *(c.category2Do.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *category2) updateTableName(table string) *category2 {
	c.ALL = field.NewAsterisk(table)
	c.Category2ID = field.NewInt64(table, "category2_id")
	c.Name = field.NewString(table, "name")
	c.Category1ID = field.NewInt64(table, "category1_id")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *category2) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *category2) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["category2_id"] = c.Category2ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["category1_id"] = c.Category1ID
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c category2) clone(db *gorm.DB) category2 {
	c.category2Do.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c category2) replaceDB(db *gorm.DB) category2 {
	c.category2Do.ReplaceDB(db)
	return c
}

type category2Do struct{ gen.DO }

type ICategory2Do interface {
	gen.SubQuery
	Debug() ICategory2Do
	WithContext(ctx context.Context) ICategory2Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICategory2Do
	WriteDB() ICategory2Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICategory2Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICategory2Do
	Not(conds ...gen.Condition) ICategory2Do
	Or(conds ...gen.Condition) ICategory2Do
	Select(conds ...field.Expr) ICategory2Do
	Where(conds ...gen.Condition) ICategory2Do
	Order(conds ...field.Expr) ICategory2Do
	Distinct(cols ...field.Expr) ICategory2Do
	Omit(cols ...field.Expr) ICategory2Do
	Join(table schema.Tabler, on ...field.Expr) ICategory2Do
	LeftJoin(table schema.Tabler, on ...field.Expr) ICategory2Do
	RightJoin(table schema.Tabler, on ...field.Expr) ICategory2Do
	Group(cols ...field.Expr) ICategory2Do
	Having(conds ...gen.Condition) ICategory2Do
	Limit(limit int) ICategory2Do
	Offset(offset int) ICategory2Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICategory2Do
	Unscoped() ICategory2Do
	Create(values ...*model.Category2) error
	CreateInBatches(values []*model.Category2, batchSize int) error
	Save(values ...*model.Category2) error
	First() (*model.Category2, error)
	Take() (*model.Category2, error)
	Last() (*model.Category2, error)
	Find() ([]*model.Category2, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Category2, err error)
	FindInBatches(result *[]*model.Category2, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Category2) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICategory2Do
	Assign(attrs ...field.AssignExpr) ICategory2Do
	Joins(fields ...field.RelationField) ICategory2Do
	Preload(fields ...field.RelationField) ICategory2Do
	FirstOrInit() (*model.Category2, error)
	FirstOrCreate() (*model.Category2, error)
	FindByPage(offset int, limit int) (result []*model.Category2, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICategory2Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c category2Do) Debug() ICategory2Do {
	return c.withDO(c.DO.Debug())
}

func (c category2Do) WithContext(ctx context.Context) ICategory2Do {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c category2Do) ReadDB() ICategory2Do {
	return c.Clauses(dbresolver.Read)
}

func (c category2Do) WriteDB() ICategory2Do {
	return c.Clauses(dbresolver.Write)
}

func (c category2Do) Session(config *gorm.Session) ICategory2Do {
	return c.withDO(c.DO.Session(config))
}

func (c category2Do) Clauses(conds ...clause.Expression) ICategory2Do {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c category2Do) Returning(value interface{}, columns ...string) ICategory2Do {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c category2Do) Not(conds ...gen.Condition) ICategory2Do {
	return c.withDO(c.DO.Not(conds...))
}

func (c category2Do) Or(conds ...gen.Condition) ICategory2Do {
	return c.withDO(c.DO.Or(conds...))
}

func (c category2Do) Select(conds ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Select(conds...))
}

func (c category2Do) Where(conds ...gen.Condition) ICategory2Do {
	return c.withDO(c.DO.Where(conds...))
}

func (c category2Do) Order(conds ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Order(conds...))
}

func (c category2Do) Distinct(cols ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c category2Do) Omit(cols ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Omit(cols...))
}

func (c category2Do) Join(table schema.Tabler, on ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Join(table, on...))
}

func (c category2Do) LeftJoin(table schema.Tabler, on ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c category2Do) RightJoin(table schema.Tabler, on ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c category2Do) Group(cols ...field.Expr) ICategory2Do {
	return c.withDO(c.DO.Group(cols...))
}

func (c category2Do) Having(conds ...gen.Condition) ICategory2Do {
	return c.withDO(c.DO.Having(conds...))
}

func (c category2Do) Limit(limit int) ICategory2Do {
	return c.withDO(c.DO.Limit(limit))
}

func (c category2Do) Offset(offset int) ICategory2Do {
	return c.withDO(c.DO.Offset(offset))
}

func (c category2Do) Scopes(funcs ...func(gen.Dao) gen.Dao) ICategory2Do {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c category2Do) Unscoped() ICategory2Do {
	return c.withDO(c.DO.Unscoped())
}

func (c category2Do) Create(values ...*model.Category2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c category2Do) CreateInBatches(values []*model.Category2, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c category2Do) Save(values ...*model.Category2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c category2Do) First() (*model.Category2, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category2), nil
	}
}

func (c category2Do) Take() (*model.Category2, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category2), nil
	}
}

func (c category2Do) Last() (*model.Category2, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category2), nil
	}
}

func (c category2Do) Find() ([]*model.Category2, error) {
	result, err := c.DO.Find()
	return result.([]*model.Category2), err
}

func (c category2Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Category2, err error) {
	buf := make([]*model.Category2, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c category2Do) FindInBatches(result *[]*model.Category2, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c category2Do) Attrs(attrs ...field.AssignExpr) ICategory2Do {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c category2Do) Assign(attrs ...field.AssignExpr) ICategory2Do {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c category2Do) Joins(fields ...field.RelationField) ICategory2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c category2Do) Preload(fields ...field.RelationField) ICategory2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c category2Do) FirstOrInit() (*model.Category2, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category2), nil
	}
}

func (c category2Do) FirstOrCreate() (*model.Category2, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Category2), nil
	}
}

func (c category2Do) FindByPage(offset int, limit int) (result []*model.Category2, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c category2Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c category2Do) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c category2Do) Delete(models ...*model.Category2) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *category2Do) withDO(do gen.Dao) *category2Do {
	c.DO = *do.(*gen.DO)
	return c
}
