// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Attr             *attr
	AttrValue        *attrValue
	Category1        *category1
	Category2        *category2
	Category3        *category3
	Menu             *menu
	Role             *role
	RoleMenu         *roleMenu
	SaleAttr         *saleAttr
	SaleAttrValue    *saleAttrValue
	Sku              *sku
	SkuAttrValue     *skuAttrValue
	SkuImage         *skuImage
	SkuSaleAttrValue *skuSaleAttrValue
	Spu              *spu
	SpuImageList     *spuImageList
	SpuSaleAttr      *spuSaleAttr
	Trademark        *trademark
	User             *user
	UserRole         *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Attr = &Q.Attr
	AttrValue = &Q.AttrValue
	Category1 = &Q.Category1
	Category2 = &Q.Category2
	Category3 = &Q.Category3
	Menu = &Q.Menu
	Role = &Q.Role
	RoleMenu = &Q.RoleMenu
	SaleAttr = &Q.SaleAttr
	SaleAttrValue = &Q.SaleAttrValue
	Sku = &Q.Sku
	SkuAttrValue = &Q.SkuAttrValue
	SkuImage = &Q.SkuImage
	SkuSaleAttrValue = &Q.SkuSaleAttrValue
	Spu = &Q.Spu
	SpuImageList = &Q.SpuImageList
	SpuSaleAttr = &Q.SpuSaleAttr
	Trademark = &Q.Trademark
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Attr:             newAttr(db, opts...),
		AttrValue:        newAttrValue(db, opts...),
		Category1:        newCategory1(db, opts...),
		Category2:        newCategory2(db, opts...),
		Category3:        newCategory3(db, opts...),
		Menu:             newMenu(db, opts...),
		Role:             newRole(db, opts...),
		RoleMenu:         newRoleMenu(db, opts...),
		SaleAttr:         newSaleAttr(db, opts...),
		SaleAttrValue:    newSaleAttrValue(db, opts...),
		Sku:              newSku(db, opts...),
		SkuAttrValue:     newSkuAttrValue(db, opts...),
		SkuImage:         newSkuImage(db, opts...),
		SkuSaleAttrValue: newSkuSaleAttrValue(db, opts...),
		Spu:              newSpu(db, opts...),
		SpuImageList:     newSpuImageList(db, opts...),
		SpuSaleAttr:      newSpuSaleAttr(db, opts...),
		Trademark:        newTrademark(db, opts...),
		User:             newUser(db, opts...),
		UserRole:         newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Attr             attr
	AttrValue        attrValue
	Category1        category1
	Category2        category2
	Category3        category3
	Menu             menu
	Role             role
	RoleMenu         roleMenu
	SaleAttr         saleAttr
	SaleAttrValue    saleAttrValue
	Sku              sku
	SkuAttrValue     skuAttrValue
	SkuImage         skuImage
	SkuSaleAttrValue skuSaleAttrValue
	Spu              spu
	SpuImageList     spuImageList
	SpuSaleAttr      spuSaleAttr
	Trademark        trademark
	User             user
	UserRole         userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Attr:             q.Attr.clone(db),
		AttrValue:        q.AttrValue.clone(db),
		Category1:        q.Category1.clone(db),
		Category2:        q.Category2.clone(db),
		Category3:        q.Category3.clone(db),
		Menu:             q.Menu.clone(db),
		Role:             q.Role.clone(db),
		RoleMenu:         q.RoleMenu.clone(db),
		SaleAttr:         q.SaleAttr.clone(db),
		SaleAttrValue:    q.SaleAttrValue.clone(db),
		Sku:              q.Sku.clone(db),
		SkuAttrValue:     q.SkuAttrValue.clone(db),
		SkuImage:         q.SkuImage.clone(db),
		SkuSaleAttrValue: q.SkuSaleAttrValue.clone(db),
		Spu:              q.Spu.clone(db),
		SpuImageList:     q.SpuImageList.clone(db),
		SpuSaleAttr:      q.SpuSaleAttr.clone(db),
		Trademark:        q.Trademark.clone(db),
		User:             q.User.clone(db),
		UserRole:         q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Attr:             q.Attr.replaceDB(db),
		AttrValue:        q.AttrValue.replaceDB(db),
		Category1:        q.Category1.replaceDB(db),
		Category2:        q.Category2.replaceDB(db),
		Category3:        q.Category3.replaceDB(db),
		Menu:             q.Menu.replaceDB(db),
		Role:             q.Role.replaceDB(db),
		RoleMenu:         q.RoleMenu.replaceDB(db),
		SaleAttr:         q.SaleAttr.replaceDB(db),
		SaleAttrValue:    q.SaleAttrValue.replaceDB(db),
		Sku:              q.Sku.replaceDB(db),
		SkuAttrValue:     q.SkuAttrValue.replaceDB(db),
		SkuImage:         q.SkuImage.replaceDB(db),
		SkuSaleAttrValue: q.SkuSaleAttrValue.replaceDB(db),
		Spu:              q.Spu.replaceDB(db),
		SpuImageList:     q.SpuImageList.replaceDB(db),
		SpuSaleAttr:      q.SpuSaleAttr.replaceDB(db),
		Trademark:        q.Trademark.replaceDB(db),
		User:             q.User.replaceDB(db),
		UserRole:         q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Attr             IAttrDo
	AttrValue        IAttrValueDo
	Category1        ICategory1Do
	Category2        ICategory2Do
	Category3        ICategory3Do
	Menu             IMenuDo
	Role             IRoleDo
	RoleMenu         IRoleMenuDo
	SaleAttr         ISaleAttrDo
	SaleAttrValue    ISaleAttrValueDo
	Sku              ISkuDo
	SkuAttrValue     ISkuAttrValueDo
	SkuImage         ISkuImageDo
	SkuSaleAttrValue ISkuSaleAttrValueDo
	Spu              ISpuDo
	SpuImageList     ISpuImageListDo
	SpuSaleAttr      ISpuSaleAttrDo
	Trademark        ITrademarkDo
	User             IUserDo
	UserRole         IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Attr:             q.Attr.WithContext(ctx),
		AttrValue:        q.AttrValue.WithContext(ctx),
		Category1:        q.Category1.WithContext(ctx),
		Category2:        q.Category2.WithContext(ctx),
		Category3:        q.Category3.WithContext(ctx),
		Menu:             q.Menu.WithContext(ctx),
		Role:             q.Role.WithContext(ctx),
		RoleMenu:         q.RoleMenu.WithContext(ctx),
		SaleAttr:         q.SaleAttr.WithContext(ctx),
		SaleAttrValue:    q.SaleAttrValue.WithContext(ctx),
		Sku:              q.Sku.WithContext(ctx),
		SkuAttrValue:     q.SkuAttrValue.WithContext(ctx),
		SkuImage:         q.SkuImage.WithContext(ctx),
		SkuSaleAttrValue: q.SkuSaleAttrValue.WithContext(ctx),
		Spu:              q.Spu.WithContext(ctx),
		SpuImageList:     q.SpuImageList.WithContext(ctx),
		SpuSaleAttr:      q.SpuSaleAttr.WithContext(ctx),
		Trademark:        q.Trademark.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UserRole:         q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
