// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSaleAttrValue(db *gorm.DB, opts ...gen.DOOption) saleAttrValue {
	_saleAttrValue := saleAttrValue{}

	_saleAttrValue.saleAttrValueDo.UseDB(db, opts...)
	_saleAttrValue.saleAttrValueDo.UseModel(&model.SaleAttrValue{})

	tableName := _saleAttrValue.saleAttrValueDo.TableName()
	_saleAttrValue.ALL = field.NewAsterisk(tableName)
	_saleAttrValue.SaleAttrValueID = field.NewInt64(tableName, "sale_attr_value_id")
	_saleAttrValue.SpuID = field.NewInt64(tableName, "spu_id")
	_saleAttrValue.SaleAttrID = field.NewInt64(tableName, "sale_attr_id")
	_saleAttrValue.SaleAttrValueName = field.NewString(tableName, "sale_attr_value_name")
	_saleAttrValue.CreateTime = field.NewTime(tableName, "create_time")
	_saleAttrValue.UpdateTime = field.NewTime(tableName, "update_time")

	_saleAttrValue.fillFieldMap()

	return _saleAttrValue
}

type saleAttrValue struct {
	saleAttrValueDo

	ALL               field.Asterisk
	SaleAttrValueID   field.Int64
	SpuID             field.Int64
	SaleAttrID        field.Int64
	SaleAttrValueName field.String
	CreateTime        field.Time
	UpdateTime        field.Time

	fieldMap map[string]field.Expr
}

func (s saleAttrValue) Table(newTableName string) *saleAttrValue {
	s.saleAttrValueDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s saleAttrValue) As(alias string) *saleAttrValue {
	s.saleAttrValueDo.DO = *(s.saleAttrValueDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *saleAttrValue) updateTableName(table string) *saleAttrValue {
	s.ALL = field.NewAsterisk(table)
	s.SaleAttrValueID = field.NewInt64(table, "sale_attr_value_id")
	s.SpuID = field.NewInt64(table, "spu_id")
	s.SaleAttrID = field.NewInt64(table, "sale_attr_id")
	s.SaleAttrValueName = field.NewString(table, "sale_attr_value_name")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *saleAttrValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *saleAttrValue) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["sale_attr_value_id"] = s.SaleAttrValueID
	s.fieldMap["spu_id"] = s.SpuID
	s.fieldMap["sale_attr_id"] = s.SaleAttrID
	s.fieldMap["sale_attr_value_name"] = s.SaleAttrValueName
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s saleAttrValue) clone(db *gorm.DB) saleAttrValue {
	s.saleAttrValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s saleAttrValue) replaceDB(db *gorm.DB) saleAttrValue {
	s.saleAttrValueDo.ReplaceDB(db)
	return s
}

type saleAttrValueDo struct{ gen.DO }

type ISaleAttrValueDo interface {
	gen.SubQuery
	Debug() ISaleAttrValueDo
	WithContext(ctx context.Context) ISaleAttrValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISaleAttrValueDo
	WriteDB() ISaleAttrValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISaleAttrValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISaleAttrValueDo
	Not(conds ...gen.Condition) ISaleAttrValueDo
	Or(conds ...gen.Condition) ISaleAttrValueDo
	Select(conds ...field.Expr) ISaleAttrValueDo
	Where(conds ...gen.Condition) ISaleAttrValueDo
	Order(conds ...field.Expr) ISaleAttrValueDo
	Distinct(cols ...field.Expr) ISaleAttrValueDo
	Omit(cols ...field.Expr) ISaleAttrValueDo
	Join(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo
	Group(cols ...field.Expr) ISaleAttrValueDo
	Having(conds ...gen.Condition) ISaleAttrValueDo
	Limit(limit int) ISaleAttrValueDo
	Offset(offset int) ISaleAttrValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISaleAttrValueDo
	Unscoped() ISaleAttrValueDo
	Create(values ...*model.SaleAttrValue) error
	CreateInBatches(values []*model.SaleAttrValue, batchSize int) error
	Save(values ...*model.SaleAttrValue) error
	First() (*model.SaleAttrValue, error)
	Take() (*model.SaleAttrValue, error)
	Last() (*model.SaleAttrValue, error)
	Find() ([]*model.SaleAttrValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SaleAttrValue, err error)
	FindInBatches(result *[]*model.SaleAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SaleAttrValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISaleAttrValueDo
	Assign(attrs ...field.AssignExpr) ISaleAttrValueDo
	Joins(fields ...field.RelationField) ISaleAttrValueDo
	Preload(fields ...field.RelationField) ISaleAttrValueDo
	FirstOrInit() (*model.SaleAttrValue, error)
	FirstOrCreate() (*model.SaleAttrValue, error)
	FindByPage(offset int, limit int) (result []*model.SaleAttrValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISaleAttrValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s saleAttrValueDo) Debug() ISaleAttrValueDo {
	return s.withDO(s.DO.Debug())
}

func (s saleAttrValueDo) WithContext(ctx context.Context) ISaleAttrValueDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s saleAttrValueDo) ReadDB() ISaleAttrValueDo {
	return s.Clauses(dbresolver.Read)
}

func (s saleAttrValueDo) WriteDB() ISaleAttrValueDo {
	return s.Clauses(dbresolver.Write)
}

func (s saleAttrValueDo) Session(config *gorm.Session) ISaleAttrValueDo {
	return s.withDO(s.DO.Session(config))
}

func (s saleAttrValueDo) Clauses(conds ...clause.Expression) ISaleAttrValueDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s saleAttrValueDo) Returning(value interface{}, columns ...string) ISaleAttrValueDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s saleAttrValueDo) Not(conds ...gen.Condition) ISaleAttrValueDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s saleAttrValueDo) Or(conds ...gen.Condition) ISaleAttrValueDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s saleAttrValueDo) Select(conds ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s saleAttrValueDo) Where(conds ...gen.Condition) ISaleAttrValueDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s saleAttrValueDo) Order(conds ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s saleAttrValueDo) Distinct(cols ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s saleAttrValueDo) Omit(cols ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s saleAttrValueDo) Join(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s saleAttrValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s saleAttrValueDo) RightJoin(table schema.Tabler, on ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s saleAttrValueDo) Group(cols ...field.Expr) ISaleAttrValueDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s saleAttrValueDo) Having(conds ...gen.Condition) ISaleAttrValueDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s saleAttrValueDo) Limit(limit int) ISaleAttrValueDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s saleAttrValueDo) Offset(offset int) ISaleAttrValueDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s saleAttrValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISaleAttrValueDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s saleAttrValueDo) Unscoped() ISaleAttrValueDo {
	return s.withDO(s.DO.Unscoped())
}

func (s saleAttrValueDo) Create(values ...*model.SaleAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s saleAttrValueDo) CreateInBatches(values []*model.SaleAttrValue, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s saleAttrValueDo) Save(values ...*model.SaleAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s saleAttrValueDo) First() (*model.SaleAttrValue, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttrValue), nil
	}
}

func (s saleAttrValueDo) Take() (*model.SaleAttrValue, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttrValue), nil
	}
}

func (s saleAttrValueDo) Last() (*model.SaleAttrValue, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttrValue), nil
	}
}

func (s saleAttrValueDo) Find() ([]*model.SaleAttrValue, error) {
	result, err := s.DO.Find()
	return result.([]*model.SaleAttrValue), err
}

func (s saleAttrValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SaleAttrValue, err error) {
	buf := make([]*model.SaleAttrValue, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s saleAttrValueDo) FindInBatches(result *[]*model.SaleAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s saleAttrValueDo) Attrs(attrs ...field.AssignExpr) ISaleAttrValueDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s saleAttrValueDo) Assign(attrs ...field.AssignExpr) ISaleAttrValueDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s saleAttrValueDo) Joins(fields ...field.RelationField) ISaleAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s saleAttrValueDo) Preload(fields ...field.RelationField) ISaleAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s saleAttrValueDo) FirstOrInit() (*model.SaleAttrValue, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttrValue), nil
	}
}

func (s saleAttrValueDo) FirstOrCreate() (*model.SaleAttrValue, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttrValue), nil
	}
}

func (s saleAttrValueDo) FindByPage(offset int, limit int) (result []*model.SaleAttrValue, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s saleAttrValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s saleAttrValueDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s saleAttrValueDo) Delete(models ...*model.SaleAttrValue) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *saleAttrValueDo) withDO(do gen.Dao) *saleAttrValueDo {
	s.DO = *do.(*gen.DO)
	return s
}
