// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSaleAttr(db *gorm.DB, opts ...gen.DOOption) saleAttr {
	_saleAttr := saleAttr{}

	_saleAttr.saleAttrDo.UseDB(db, opts...)
	_saleAttr.saleAttrDo.UseModel(&model.SaleAttr{})

	tableName := _saleAttr.saleAttrDo.TableName()
	_saleAttr.ALL = field.NewAsterisk(tableName)
	_saleAttr.SaleAttrID = field.NewInt64(tableName, "sale_attr_id")
	_saleAttr.SaleAttrName = field.NewString(tableName, "sale_attr_name")
	_saleAttr.CreateTime = field.NewTime(tableName, "create_time")
	_saleAttr.UpdateTime = field.NewTime(tableName, "update_time")

	_saleAttr.fillFieldMap()

	return _saleAttr
}

type saleAttr struct {
	saleAttrDo

	ALL          field.Asterisk
	SaleAttrID   field.Int64
	SaleAttrName field.String
	CreateTime   field.Time
	UpdateTime   field.Time

	fieldMap map[string]field.Expr
}

func (s saleAttr) Table(newTableName string) *saleAttr {
	s.saleAttrDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s saleAttr) As(alias string) *saleAttr {
	s.saleAttrDo.DO = *(s.saleAttrDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *saleAttr) updateTableName(table string) *saleAttr {
	s.ALL = field.NewAsterisk(table)
	s.SaleAttrID = field.NewInt64(table, "sale_attr_id")
	s.SaleAttrName = field.NewString(table, "sale_attr_name")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *saleAttr) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *saleAttr) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["sale_attr_id"] = s.SaleAttrID
	s.fieldMap["sale_attr_name"] = s.SaleAttrName
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s saleAttr) clone(db *gorm.DB) saleAttr {
	s.saleAttrDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s saleAttr) replaceDB(db *gorm.DB) saleAttr {
	s.saleAttrDo.ReplaceDB(db)
	return s
}

type saleAttrDo struct{ gen.DO }

type ISaleAttrDo interface {
	gen.SubQuery
	Debug() ISaleAttrDo
	WithContext(ctx context.Context) ISaleAttrDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISaleAttrDo
	WriteDB() ISaleAttrDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISaleAttrDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISaleAttrDo
	Not(conds ...gen.Condition) ISaleAttrDo
	Or(conds ...gen.Condition) ISaleAttrDo
	Select(conds ...field.Expr) ISaleAttrDo
	Where(conds ...gen.Condition) ISaleAttrDo
	Order(conds ...field.Expr) ISaleAttrDo
	Distinct(cols ...field.Expr) ISaleAttrDo
	Omit(cols ...field.Expr) ISaleAttrDo
	Join(table schema.Tabler, on ...field.Expr) ISaleAttrDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISaleAttrDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISaleAttrDo
	Group(cols ...field.Expr) ISaleAttrDo
	Having(conds ...gen.Condition) ISaleAttrDo
	Limit(limit int) ISaleAttrDo
	Offset(offset int) ISaleAttrDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISaleAttrDo
	Unscoped() ISaleAttrDo
	Create(values ...*model.SaleAttr) error
	CreateInBatches(values []*model.SaleAttr, batchSize int) error
	Save(values ...*model.SaleAttr) error
	First() (*model.SaleAttr, error)
	Take() (*model.SaleAttr, error)
	Last() (*model.SaleAttr, error)
	Find() ([]*model.SaleAttr, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SaleAttr, err error)
	FindInBatches(result *[]*model.SaleAttr, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SaleAttr) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISaleAttrDo
	Assign(attrs ...field.AssignExpr) ISaleAttrDo
	Joins(fields ...field.RelationField) ISaleAttrDo
	Preload(fields ...field.RelationField) ISaleAttrDo
	FirstOrInit() (*model.SaleAttr, error)
	FirstOrCreate() (*model.SaleAttr, error)
	FindByPage(offset int, limit int) (result []*model.SaleAttr, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISaleAttrDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s saleAttrDo) Debug() ISaleAttrDo {
	return s.withDO(s.DO.Debug())
}

func (s saleAttrDo) WithContext(ctx context.Context) ISaleAttrDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s saleAttrDo) ReadDB() ISaleAttrDo {
	return s.Clauses(dbresolver.Read)
}

func (s saleAttrDo) WriteDB() ISaleAttrDo {
	return s.Clauses(dbresolver.Write)
}

func (s saleAttrDo) Session(config *gorm.Session) ISaleAttrDo {
	return s.withDO(s.DO.Session(config))
}

func (s saleAttrDo) Clauses(conds ...clause.Expression) ISaleAttrDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s saleAttrDo) Returning(value interface{}, columns ...string) ISaleAttrDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s saleAttrDo) Not(conds ...gen.Condition) ISaleAttrDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s saleAttrDo) Or(conds ...gen.Condition) ISaleAttrDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s saleAttrDo) Select(conds ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s saleAttrDo) Where(conds ...gen.Condition) ISaleAttrDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s saleAttrDo) Order(conds ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s saleAttrDo) Distinct(cols ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s saleAttrDo) Omit(cols ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s saleAttrDo) Join(table schema.Tabler, on ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s saleAttrDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s saleAttrDo) RightJoin(table schema.Tabler, on ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s saleAttrDo) Group(cols ...field.Expr) ISaleAttrDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s saleAttrDo) Having(conds ...gen.Condition) ISaleAttrDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s saleAttrDo) Limit(limit int) ISaleAttrDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s saleAttrDo) Offset(offset int) ISaleAttrDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s saleAttrDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISaleAttrDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s saleAttrDo) Unscoped() ISaleAttrDo {
	return s.withDO(s.DO.Unscoped())
}

func (s saleAttrDo) Create(values ...*model.SaleAttr) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s saleAttrDo) CreateInBatches(values []*model.SaleAttr, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s saleAttrDo) Save(values ...*model.SaleAttr) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s saleAttrDo) First() (*model.SaleAttr, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttr), nil
	}
}

func (s saleAttrDo) Take() (*model.SaleAttr, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttr), nil
	}
}

func (s saleAttrDo) Last() (*model.SaleAttr, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttr), nil
	}
}

func (s saleAttrDo) Find() ([]*model.SaleAttr, error) {
	result, err := s.DO.Find()
	return result.([]*model.SaleAttr), err
}

func (s saleAttrDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SaleAttr, err error) {
	buf := make([]*model.SaleAttr, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s saleAttrDo) FindInBatches(result *[]*model.SaleAttr, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s saleAttrDo) Attrs(attrs ...field.AssignExpr) ISaleAttrDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s saleAttrDo) Assign(attrs ...field.AssignExpr) ISaleAttrDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s saleAttrDo) Joins(fields ...field.RelationField) ISaleAttrDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s saleAttrDo) Preload(fields ...field.RelationField) ISaleAttrDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s saleAttrDo) FirstOrInit() (*model.SaleAttr, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttr), nil
	}
}

func (s saleAttrDo) FirstOrCreate() (*model.SaleAttr, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SaleAttr), nil
	}
}

func (s saleAttrDo) FindByPage(offset int, limit int) (result []*model.SaleAttr, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s saleAttrDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s saleAttrDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s saleAttrDo) Delete(models ...*model.SaleAttr) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *saleAttrDo) withDO(do gen.Dao) *saleAttrDo {
	s.DO = *do.(*gen.DO)
	return s
}
