// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSkuAttrValue(db *gorm.DB, opts ...gen.DOOption) skuAttrValue {
	_skuAttrValue := skuAttrValue{}

	_skuAttrValue.skuAttrValueDo.UseDB(db, opts...)
	_skuAttrValue.skuAttrValueDo.UseModel(&model.SkuAttrValue{})

	tableName := _skuAttrValue.skuAttrValueDo.TableName()
	_skuAttrValue.ALL = field.NewAsterisk(tableName)
	_skuAttrValue.SkuAttrValueID = field.NewInt64(tableName, "sku_attr_value_id")
	_skuAttrValue.AttrID = field.NewInt64(tableName, "attr_id")
	_skuAttrValue.SkuID = field.NewInt64(tableName, "sku_id")
	_skuAttrValue.AttrValueID = field.NewInt64(tableName, "attr_value_id")
	_skuAttrValue.CreateTime = field.NewTime(tableName, "create_time")
	_skuAttrValue.UpdateTime = field.NewTime(tableName, "update_time")

	_skuAttrValue.fillFieldMap()

	return _skuAttrValue
}

type skuAttrValue struct {
	skuAttrValueDo

	ALL            field.Asterisk
	SkuAttrValueID field.Int64
	AttrID         field.Int64
	SkuID          field.Int64
	AttrValueID    field.Int64
	CreateTime     field.Time
	UpdateTime     field.Time

	fieldMap map[string]field.Expr
}

func (s skuAttrValue) Table(newTableName string) *skuAttrValue {
	s.skuAttrValueDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skuAttrValue) As(alias string) *skuAttrValue {
	s.skuAttrValueDo.DO = *(s.skuAttrValueDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skuAttrValue) updateTableName(table string) *skuAttrValue {
	s.ALL = field.NewAsterisk(table)
	s.SkuAttrValueID = field.NewInt64(table, "sku_attr_value_id")
	s.AttrID = field.NewInt64(table, "attr_id")
	s.SkuID = field.NewInt64(table, "sku_id")
	s.AttrValueID = field.NewInt64(table, "attr_value_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *skuAttrValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skuAttrValue) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["sku_attr_value_id"] = s.SkuAttrValueID
	s.fieldMap["attr_id"] = s.AttrID
	s.fieldMap["sku_id"] = s.SkuID
	s.fieldMap["attr_value_id"] = s.AttrValueID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s skuAttrValue) clone(db *gorm.DB) skuAttrValue {
	s.skuAttrValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skuAttrValue) replaceDB(db *gorm.DB) skuAttrValue {
	s.skuAttrValueDo.ReplaceDB(db)
	return s
}

type skuAttrValueDo struct{ gen.DO }

type ISkuAttrValueDo interface {
	gen.SubQuery
	Debug() ISkuAttrValueDo
	WithContext(ctx context.Context) ISkuAttrValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISkuAttrValueDo
	WriteDB() ISkuAttrValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISkuAttrValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISkuAttrValueDo
	Not(conds ...gen.Condition) ISkuAttrValueDo
	Or(conds ...gen.Condition) ISkuAttrValueDo
	Select(conds ...field.Expr) ISkuAttrValueDo
	Where(conds ...gen.Condition) ISkuAttrValueDo
	Order(conds ...field.Expr) ISkuAttrValueDo
	Distinct(cols ...field.Expr) ISkuAttrValueDo
	Omit(cols ...field.Expr) ISkuAttrValueDo
	Join(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo
	Group(cols ...field.Expr) ISkuAttrValueDo
	Having(conds ...gen.Condition) ISkuAttrValueDo
	Limit(limit int) ISkuAttrValueDo
	Offset(offset int) ISkuAttrValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuAttrValueDo
	Unscoped() ISkuAttrValueDo
	Create(values ...*model.SkuAttrValue) error
	CreateInBatches(values []*model.SkuAttrValue, batchSize int) error
	Save(values ...*model.SkuAttrValue) error
	First() (*model.SkuAttrValue, error)
	Take() (*model.SkuAttrValue, error)
	Last() (*model.SkuAttrValue, error)
	Find() ([]*model.SkuAttrValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuAttrValue, err error)
	FindInBatches(result *[]*model.SkuAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SkuAttrValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISkuAttrValueDo
	Assign(attrs ...field.AssignExpr) ISkuAttrValueDo
	Joins(fields ...field.RelationField) ISkuAttrValueDo
	Preload(fields ...field.RelationField) ISkuAttrValueDo
	FirstOrInit() (*model.SkuAttrValue, error)
	FirstOrCreate() (*model.SkuAttrValue, error)
	FindByPage(offset int, limit int) (result []*model.SkuAttrValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISkuAttrValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s skuAttrValueDo) Debug() ISkuAttrValueDo {
	return s.withDO(s.DO.Debug())
}

func (s skuAttrValueDo) WithContext(ctx context.Context) ISkuAttrValueDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skuAttrValueDo) ReadDB() ISkuAttrValueDo {
	return s.Clauses(dbresolver.Read)
}

func (s skuAttrValueDo) WriteDB() ISkuAttrValueDo {
	return s.Clauses(dbresolver.Write)
}

func (s skuAttrValueDo) Session(config *gorm.Session) ISkuAttrValueDo {
	return s.withDO(s.DO.Session(config))
}

func (s skuAttrValueDo) Clauses(conds ...clause.Expression) ISkuAttrValueDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skuAttrValueDo) Returning(value interface{}, columns ...string) ISkuAttrValueDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skuAttrValueDo) Not(conds ...gen.Condition) ISkuAttrValueDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skuAttrValueDo) Or(conds ...gen.Condition) ISkuAttrValueDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skuAttrValueDo) Select(conds ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skuAttrValueDo) Where(conds ...gen.Condition) ISkuAttrValueDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skuAttrValueDo) Order(conds ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skuAttrValueDo) Distinct(cols ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skuAttrValueDo) Omit(cols ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skuAttrValueDo) Join(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skuAttrValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skuAttrValueDo) RightJoin(table schema.Tabler, on ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skuAttrValueDo) Group(cols ...field.Expr) ISkuAttrValueDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skuAttrValueDo) Having(conds ...gen.Condition) ISkuAttrValueDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skuAttrValueDo) Limit(limit int) ISkuAttrValueDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skuAttrValueDo) Offset(offset int) ISkuAttrValueDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skuAttrValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuAttrValueDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skuAttrValueDo) Unscoped() ISkuAttrValueDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skuAttrValueDo) Create(values ...*model.SkuAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skuAttrValueDo) CreateInBatches(values []*model.SkuAttrValue, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skuAttrValueDo) Save(values ...*model.SkuAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skuAttrValueDo) First() (*model.SkuAttrValue, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuAttrValue), nil
	}
}

func (s skuAttrValueDo) Take() (*model.SkuAttrValue, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuAttrValue), nil
	}
}

func (s skuAttrValueDo) Last() (*model.SkuAttrValue, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuAttrValue), nil
	}
}

func (s skuAttrValueDo) Find() ([]*model.SkuAttrValue, error) {
	result, err := s.DO.Find()
	return result.([]*model.SkuAttrValue), err
}

func (s skuAttrValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuAttrValue, err error) {
	buf := make([]*model.SkuAttrValue, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skuAttrValueDo) FindInBatches(result *[]*model.SkuAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skuAttrValueDo) Attrs(attrs ...field.AssignExpr) ISkuAttrValueDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skuAttrValueDo) Assign(attrs ...field.AssignExpr) ISkuAttrValueDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skuAttrValueDo) Joins(fields ...field.RelationField) ISkuAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skuAttrValueDo) Preload(fields ...field.RelationField) ISkuAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skuAttrValueDo) FirstOrInit() (*model.SkuAttrValue, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuAttrValue), nil
	}
}

func (s skuAttrValueDo) FirstOrCreate() (*model.SkuAttrValue, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuAttrValue), nil
	}
}

func (s skuAttrValueDo) FindByPage(offset int, limit int) (result []*model.SkuAttrValue, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skuAttrValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skuAttrValueDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skuAttrValueDo) Delete(models ...*model.SkuAttrValue) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skuAttrValueDo) withDO(do gen.Dao) *skuAttrValueDo {
	s.DO = *do.(*gen.DO)
	return s
}
