// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSkuImage(db *gorm.DB, opts ...gen.DOOption) skuImage {
	_skuImage := skuImage{}

	_skuImage.skuImageDo.UseDB(db, opts...)
	_skuImage.skuImageDo.UseModel(&model.SkuImage{})

	tableName := _skuImage.skuImageDo.TableName()
	_skuImage.ALL = field.NewAsterisk(tableName)
	_skuImage.ImageID = field.NewInt64(tableName, "image_id")
	_skuImage.SkuID = field.NewInt64(tableName, "sku_id")
	_skuImage.ImageURL = field.NewString(tableName, "image_url")
	_skuImage.SpuImageID = field.NewInt64(tableName, "spu_image_id")
	_skuImage.IsDefault = field.NewBool(tableName, "is_default")
	_skuImage.CreateTime = field.NewTime(tableName, "create_time")
	_skuImage.UpdateTime = field.NewTime(tableName, "update_time")

	_skuImage.fillFieldMap()

	return _skuImage
}

type skuImage struct {
	skuImageDo

	ALL        field.Asterisk
	ImageID    field.Int64
	SkuID      field.Int64
	ImageURL   field.String
	SpuImageID field.Int64
	IsDefault  field.Bool // 是否默认图片（true=默认，false=否）
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (s skuImage) Table(newTableName string) *skuImage {
	s.skuImageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skuImage) As(alias string) *skuImage {
	s.skuImageDo.DO = *(s.skuImageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skuImage) updateTableName(table string) *skuImage {
	s.ALL = field.NewAsterisk(table)
	s.ImageID = field.NewInt64(table, "image_id")
	s.SkuID = field.NewInt64(table, "sku_id")
	s.ImageURL = field.NewString(table, "image_url")
	s.SpuImageID = field.NewInt64(table, "spu_image_id")
	s.IsDefault = field.NewBool(table, "is_default")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *skuImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skuImage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["image_id"] = s.ImageID
	s.fieldMap["sku_id"] = s.SkuID
	s.fieldMap["image_url"] = s.ImageURL
	s.fieldMap["spu_image_id"] = s.SpuImageID
	s.fieldMap["is_default"] = s.IsDefault
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s skuImage) clone(db *gorm.DB) skuImage {
	s.skuImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skuImage) replaceDB(db *gorm.DB) skuImage {
	s.skuImageDo.ReplaceDB(db)
	return s
}

type skuImageDo struct{ gen.DO }

type ISkuImageDo interface {
	gen.SubQuery
	Debug() ISkuImageDo
	WithContext(ctx context.Context) ISkuImageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISkuImageDo
	WriteDB() ISkuImageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISkuImageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISkuImageDo
	Not(conds ...gen.Condition) ISkuImageDo
	Or(conds ...gen.Condition) ISkuImageDo
	Select(conds ...field.Expr) ISkuImageDo
	Where(conds ...gen.Condition) ISkuImageDo
	Order(conds ...field.Expr) ISkuImageDo
	Distinct(cols ...field.Expr) ISkuImageDo
	Omit(cols ...field.Expr) ISkuImageDo
	Join(table schema.Tabler, on ...field.Expr) ISkuImageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISkuImageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISkuImageDo
	Group(cols ...field.Expr) ISkuImageDo
	Having(conds ...gen.Condition) ISkuImageDo
	Limit(limit int) ISkuImageDo
	Offset(offset int) ISkuImageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuImageDo
	Unscoped() ISkuImageDo
	Create(values ...*model.SkuImage) error
	CreateInBatches(values []*model.SkuImage, batchSize int) error
	Save(values ...*model.SkuImage) error
	First() (*model.SkuImage, error)
	Take() (*model.SkuImage, error)
	Last() (*model.SkuImage, error)
	Find() ([]*model.SkuImage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuImage, err error)
	FindInBatches(result *[]*model.SkuImage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SkuImage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISkuImageDo
	Assign(attrs ...field.AssignExpr) ISkuImageDo
	Joins(fields ...field.RelationField) ISkuImageDo
	Preload(fields ...field.RelationField) ISkuImageDo
	FirstOrInit() (*model.SkuImage, error)
	FirstOrCreate() (*model.SkuImage, error)
	FindByPage(offset int, limit int) (result []*model.SkuImage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISkuImageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s skuImageDo) Debug() ISkuImageDo {
	return s.withDO(s.DO.Debug())
}

func (s skuImageDo) WithContext(ctx context.Context) ISkuImageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skuImageDo) ReadDB() ISkuImageDo {
	return s.Clauses(dbresolver.Read)
}

func (s skuImageDo) WriteDB() ISkuImageDo {
	return s.Clauses(dbresolver.Write)
}

func (s skuImageDo) Session(config *gorm.Session) ISkuImageDo {
	return s.withDO(s.DO.Session(config))
}

func (s skuImageDo) Clauses(conds ...clause.Expression) ISkuImageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skuImageDo) Returning(value interface{}, columns ...string) ISkuImageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skuImageDo) Not(conds ...gen.Condition) ISkuImageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skuImageDo) Or(conds ...gen.Condition) ISkuImageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skuImageDo) Select(conds ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skuImageDo) Where(conds ...gen.Condition) ISkuImageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skuImageDo) Order(conds ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skuImageDo) Distinct(cols ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skuImageDo) Omit(cols ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skuImageDo) Join(table schema.Tabler, on ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skuImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skuImageDo) RightJoin(table schema.Tabler, on ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skuImageDo) Group(cols ...field.Expr) ISkuImageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skuImageDo) Having(conds ...gen.Condition) ISkuImageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skuImageDo) Limit(limit int) ISkuImageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skuImageDo) Offset(offset int) ISkuImageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skuImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuImageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skuImageDo) Unscoped() ISkuImageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skuImageDo) Create(values ...*model.SkuImage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skuImageDo) CreateInBatches(values []*model.SkuImage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skuImageDo) Save(values ...*model.SkuImage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skuImageDo) First() (*model.SkuImage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuImage), nil
	}
}

func (s skuImageDo) Take() (*model.SkuImage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuImage), nil
	}
}

func (s skuImageDo) Last() (*model.SkuImage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuImage), nil
	}
}

func (s skuImageDo) Find() ([]*model.SkuImage, error) {
	result, err := s.DO.Find()
	return result.([]*model.SkuImage), err
}

func (s skuImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuImage, err error) {
	buf := make([]*model.SkuImage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skuImageDo) FindInBatches(result *[]*model.SkuImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skuImageDo) Attrs(attrs ...field.AssignExpr) ISkuImageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skuImageDo) Assign(attrs ...field.AssignExpr) ISkuImageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skuImageDo) Joins(fields ...field.RelationField) ISkuImageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skuImageDo) Preload(fields ...field.RelationField) ISkuImageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skuImageDo) FirstOrInit() (*model.SkuImage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuImage), nil
	}
}

func (s skuImageDo) FirstOrCreate() (*model.SkuImage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuImage), nil
	}
}

func (s skuImageDo) FindByPage(offset int, limit int) (result []*model.SkuImage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skuImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skuImageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skuImageDo) Delete(models ...*model.SkuImage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skuImageDo) withDO(do gen.Dao) *skuImageDo {
	s.DO = *do.(*gen.DO)
	return s
}
