// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSkuSaleAttrValue(db *gorm.DB, opts ...gen.DOOption) skuSaleAttrValue {
	_skuSaleAttrValue := skuSaleAttrValue{}

	_skuSaleAttrValue.skuSaleAttrValueDo.UseDB(db, opts...)
	_skuSaleAttrValue.skuSaleAttrValueDo.UseModel(&model.SkuSaleAttrValue{})

	tableName := _skuSaleAttrValue.skuSaleAttrValueDo.TableName()
	_skuSaleAttrValue.ALL = field.NewAsterisk(tableName)
	_skuSaleAttrValue.SkuSaleAttrValueID = field.NewInt64(tableName, "sku_sale_attr_value_id")
	_skuSaleAttrValue.SkuID = field.NewInt64(tableName, "sku_id")
	_skuSaleAttrValue.SaleAttrValueID = field.NewInt64(tableName, "sale_attr_value_id")
	_skuSaleAttrValue.CreateTime = field.NewTime(tableName, "create_time")
	_skuSaleAttrValue.UpdateTime = field.NewTime(tableName, "update_time")

	_skuSaleAttrValue.fillFieldMap()

	return _skuSaleAttrValue
}

type skuSaleAttrValue struct {
	skuSaleAttrValueDo

	ALL                field.Asterisk
	SkuSaleAttrValueID field.Int64
	SkuID              field.Int64
	SaleAttrValueID    field.Int64
	CreateTime         field.Time
	UpdateTime         field.Time

	fieldMap map[string]field.Expr
}

func (s skuSaleAttrValue) Table(newTableName string) *skuSaleAttrValue {
	s.skuSaleAttrValueDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skuSaleAttrValue) As(alias string) *skuSaleAttrValue {
	s.skuSaleAttrValueDo.DO = *(s.skuSaleAttrValueDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skuSaleAttrValue) updateTableName(table string) *skuSaleAttrValue {
	s.ALL = field.NewAsterisk(table)
	s.SkuSaleAttrValueID = field.NewInt64(table, "sku_sale_attr_value_id")
	s.SkuID = field.NewInt64(table, "sku_id")
	s.SaleAttrValueID = field.NewInt64(table, "sale_attr_value_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *skuSaleAttrValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skuSaleAttrValue) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["sku_sale_attr_value_id"] = s.SkuSaleAttrValueID
	s.fieldMap["sku_id"] = s.SkuID
	s.fieldMap["sale_attr_value_id"] = s.SaleAttrValueID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s skuSaleAttrValue) clone(db *gorm.DB) skuSaleAttrValue {
	s.skuSaleAttrValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skuSaleAttrValue) replaceDB(db *gorm.DB) skuSaleAttrValue {
	s.skuSaleAttrValueDo.ReplaceDB(db)
	return s
}

type skuSaleAttrValueDo struct{ gen.DO }

type ISkuSaleAttrValueDo interface {
	gen.SubQuery
	Debug() ISkuSaleAttrValueDo
	WithContext(ctx context.Context) ISkuSaleAttrValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISkuSaleAttrValueDo
	WriteDB() ISkuSaleAttrValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISkuSaleAttrValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISkuSaleAttrValueDo
	Not(conds ...gen.Condition) ISkuSaleAttrValueDo
	Or(conds ...gen.Condition) ISkuSaleAttrValueDo
	Select(conds ...field.Expr) ISkuSaleAttrValueDo
	Where(conds ...gen.Condition) ISkuSaleAttrValueDo
	Order(conds ...field.Expr) ISkuSaleAttrValueDo
	Distinct(cols ...field.Expr) ISkuSaleAttrValueDo
	Omit(cols ...field.Expr) ISkuSaleAttrValueDo
	Join(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo
	Group(cols ...field.Expr) ISkuSaleAttrValueDo
	Having(conds ...gen.Condition) ISkuSaleAttrValueDo
	Limit(limit int) ISkuSaleAttrValueDo
	Offset(offset int) ISkuSaleAttrValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuSaleAttrValueDo
	Unscoped() ISkuSaleAttrValueDo
	Create(values ...*model.SkuSaleAttrValue) error
	CreateInBatches(values []*model.SkuSaleAttrValue, batchSize int) error
	Save(values ...*model.SkuSaleAttrValue) error
	First() (*model.SkuSaleAttrValue, error)
	Take() (*model.SkuSaleAttrValue, error)
	Last() (*model.SkuSaleAttrValue, error)
	Find() ([]*model.SkuSaleAttrValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuSaleAttrValue, err error)
	FindInBatches(result *[]*model.SkuSaleAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SkuSaleAttrValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISkuSaleAttrValueDo
	Assign(attrs ...field.AssignExpr) ISkuSaleAttrValueDo
	Joins(fields ...field.RelationField) ISkuSaleAttrValueDo
	Preload(fields ...field.RelationField) ISkuSaleAttrValueDo
	FirstOrInit() (*model.SkuSaleAttrValue, error)
	FirstOrCreate() (*model.SkuSaleAttrValue, error)
	FindByPage(offset int, limit int) (result []*model.SkuSaleAttrValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISkuSaleAttrValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s skuSaleAttrValueDo) Debug() ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Debug())
}

func (s skuSaleAttrValueDo) WithContext(ctx context.Context) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skuSaleAttrValueDo) ReadDB() ISkuSaleAttrValueDo {
	return s.Clauses(dbresolver.Read)
}

func (s skuSaleAttrValueDo) WriteDB() ISkuSaleAttrValueDo {
	return s.Clauses(dbresolver.Write)
}

func (s skuSaleAttrValueDo) Session(config *gorm.Session) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Session(config))
}

func (s skuSaleAttrValueDo) Clauses(conds ...clause.Expression) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skuSaleAttrValueDo) Returning(value interface{}, columns ...string) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skuSaleAttrValueDo) Not(conds ...gen.Condition) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skuSaleAttrValueDo) Or(conds ...gen.Condition) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skuSaleAttrValueDo) Select(conds ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skuSaleAttrValueDo) Where(conds ...gen.Condition) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skuSaleAttrValueDo) Order(conds ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skuSaleAttrValueDo) Distinct(cols ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skuSaleAttrValueDo) Omit(cols ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skuSaleAttrValueDo) Join(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skuSaleAttrValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skuSaleAttrValueDo) RightJoin(table schema.Tabler, on ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skuSaleAttrValueDo) Group(cols ...field.Expr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skuSaleAttrValueDo) Having(conds ...gen.Condition) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skuSaleAttrValueDo) Limit(limit int) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skuSaleAttrValueDo) Offset(offset int) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skuSaleAttrValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skuSaleAttrValueDo) Unscoped() ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skuSaleAttrValueDo) Create(values ...*model.SkuSaleAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skuSaleAttrValueDo) CreateInBatches(values []*model.SkuSaleAttrValue, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skuSaleAttrValueDo) Save(values ...*model.SkuSaleAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skuSaleAttrValueDo) First() (*model.SkuSaleAttrValue, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuSaleAttrValue), nil
	}
}

func (s skuSaleAttrValueDo) Take() (*model.SkuSaleAttrValue, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuSaleAttrValue), nil
	}
}

func (s skuSaleAttrValueDo) Last() (*model.SkuSaleAttrValue, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuSaleAttrValue), nil
	}
}

func (s skuSaleAttrValueDo) Find() ([]*model.SkuSaleAttrValue, error) {
	result, err := s.DO.Find()
	return result.([]*model.SkuSaleAttrValue), err
}

func (s skuSaleAttrValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkuSaleAttrValue, err error) {
	buf := make([]*model.SkuSaleAttrValue, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skuSaleAttrValueDo) FindInBatches(result *[]*model.SkuSaleAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skuSaleAttrValueDo) Attrs(attrs ...field.AssignExpr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skuSaleAttrValueDo) Assign(attrs ...field.AssignExpr) ISkuSaleAttrValueDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skuSaleAttrValueDo) Joins(fields ...field.RelationField) ISkuSaleAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skuSaleAttrValueDo) Preload(fields ...field.RelationField) ISkuSaleAttrValueDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skuSaleAttrValueDo) FirstOrInit() (*model.SkuSaleAttrValue, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuSaleAttrValue), nil
	}
}

func (s skuSaleAttrValueDo) FirstOrCreate() (*model.SkuSaleAttrValue, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkuSaleAttrValue), nil
	}
}

func (s skuSaleAttrValueDo) FindByPage(offset int, limit int) (result []*model.SkuSaleAttrValue, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skuSaleAttrValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skuSaleAttrValueDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skuSaleAttrValueDo) Delete(models ...*model.SkuSaleAttrValue) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skuSaleAttrValueDo) withDO(do gen.Dao) *skuSaleAttrValueDo {
	s.DO = *do.(*gen.DO)
	return s
}
