// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSpu(db *gorm.DB, opts ...gen.DOOption) spu {
	_spu := spu{}

	_spu.spuDo.UseDB(db, opts...)
	_spu.spuDo.UseModel(&model.Spu{})

	tableName := _spu.spuDo.TableName()
	_spu.ALL = field.NewAsterisk(tableName)
	_spu.SpuID = field.NewInt64(tableName, "spu_id")
	_spu.SpuName = field.NewString(tableName, "spu_name")
	_spu.Description = field.NewString(tableName, "description")
	_spu.Category3ID = field.NewInt64(tableName, "category3_id")
	_spu.TmID = field.NewInt64(tableName, "tm_id")
	_spu.CreateTime = field.NewTime(tableName, "create_time")
	_spu.UpdateTime = field.NewTime(tableName, "update_time")

	_spu.fillFieldMap()

	return _spu
}

type spu struct {
	spuDo

	ALL         field.Asterisk
	SpuID       field.Int64
	SpuName     field.String
	Description field.String
	Category3ID field.Int64
	TmID        field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (s spu) Table(newTableName string) *spu {
	s.spuDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s spu) As(alias string) *spu {
	s.spuDo.DO = *(s.spuDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *spu) updateTableName(table string) *spu {
	s.ALL = field.NewAsterisk(table)
	s.SpuID = field.NewInt64(table, "spu_id")
	s.SpuName = field.NewString(table, "spu_name")
	s.Description = field.NewString(table, "description")
	s.Category3ID = field.NewInt64(table, "category3_id")
	s.TmID = field.NewInt64(table, "tm_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *spu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *spu) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["spu_id"] = s.SpuID
	s.fieldMap["spu_name"] = s.SpuName
	s.fieldMap["description"] = s.Description
	s.fieldMap["category3_id"] = s.Category3ID
	s.fieldMap["tm_id"] = s.TmID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s spu) clone(db *gorm.DB) spu {
	s.spuDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s spu) replaceDB(db *gorm.DB) spu {
	s.spuDo.ReplaceDB(db)
	return s
}

type spuDo struct{ gen.DO }

type ISpuDo interface {
	gen.SubQuery
	Debug() ISpuDo
	WithContext(ctx context.Context) ISpuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpuDo
	WriteDB() ISpuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpuDo
	Not(conds ...gen.Condition) ISpuDo
	Or(conds ...gen.Condition) ISpuDo
	Select(conds ...field.Expr) ISpuDo
	Where(conds ...gen.Condition) ISpuDo
	Order(conds ...field.Expr) ISpuDo
	Distinct(cols ...field.Expr) ISpuDo
	Omit(cols ...field.Expr) ISpuDo
	Join(table schema.Tabler, on ...field.Expr) ISpuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpuDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpuDo
	Group(cols ...field.Expr) ISpuDo
	Having(conds ...gen.Condition) ISpuDo
	Limit(limit int) ISpuDo
	Offset(offset int) ISpuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuDo
	Unscoped() ISpuDo
	Create(values ...*model.Spu) error
	CreateInBatches(values []*model.Spu, batchSize int) error
	Save(values ...*model.Spu) error
	First() (*model.Spu, error)
	Take() (*model.Spu, error)
	Last() (*model.Spu, error)
	Find() ([]*model.Spu, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Spu, err error)
	FindInBatches(result *[]*model.Spu, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Spu) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpuDo
	Assign(attrs ...field.AssignExpr) ISpuDo
	Joins(fields ...field.RelationField) ISpuDo
	Preload(fields ...field.RelationField) ISpuDo
	FirstOrInit() (*model.Spu, error)
	FirstOrCreate() (*model.Spu, error)
	FindByPage(offset int, limit int) (result []*model.Spu, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s spuDo) Debug() ISpuDo {
	return s.withDO(s.DO.Debug())
}

func (s spuDo) WithContext(ctx context.Context) ISpuDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spuDo) ReadDB() ISpuDo {
	return s.Clauses(dbresolver.Read)
}

func (s spuDo) WriteDB() ISpuDo {
	return s.Clauses(dbresolver.Write)
}

func (s spuDo) Session(config *gorm.Session) ISpuDo {
	return s.withDO(s.DO.Session(config))
}

func (s spuDo) Clauses(conds ...clause.Expression) ISpuDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spuDo) Returning(value interface{}, columns ...string) ISpuDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spuDo) Not(conds ...gen.Condition) ISpuDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spuDo) Or(conds ...gen.Condition) ISpuDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spuDo) Select(conds ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spuDo) Where(conds ...gen.Condition) ISpuDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spuDo) Order(conds ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spuDo) Distinct(cols ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spuDo) Omit(cols ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spuDo) Join(table schema.Tabler, on ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spuDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpuDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spuDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpuDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spuDo) Group(cols ...field.Expr) ISpuDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spuDo) Having(conds ...gen.Condition) ISpuDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spuDo) Limit(limit int) ISpuDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spuDo) Offset(offset int) ISpuDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spuDo) Unscoped() ISpuDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spuDo) Create(values ...*model.Spu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spuDo) CreateInBatches(values []*model.Spu, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spuDo) Save(values ...*model.Spu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spuDo) First() (*model.Spu, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Spu), nil
	}
}

func (s spuDo) Take() (*model.Spu, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Spu), nil
	}
}

func (s spuDo) Last() (*model.Spu, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Spu), nil
	}
}

func (s spuDo) Find() ([]*model.Spu, error) {
	result, err := s.DO.Find()
	return result.([]*model.Spu), err
}

func (s spuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Spu, err error) {
	buf := make([]*model.Spu, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spuDo) FindInBatches(result *[]*model.Spu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spuDo) Attrs(attrs ...field.AssignExpr) ISpuDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spuDo) Assign(attrs ...field.AssignExpr) ISpuDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spuDo) Joins(fields ...field.RelationField) ISpuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spuDo) Preload(fields ...field.RelationField) ISpuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spuDo) FirstOrInit() (*model.Spu, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Spu), nil
	}
}

func (s spuDo) FirstOrCreate() (*model.Spu, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Spu), nil
	}
}

func (s spuDo) FindByPage(offset int, limit int) (result []*model.Spu, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spuDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spuDo) Delete(models ...*model.Spu) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spuDo) withDO(do gen.Dao) *spuDo {
	s.DO = *do.(*gen.DO)
	return s
}
