// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSpuImageList(db *gorm.DB, opts ...gen.DOOption) spuImageList {
	_spuImageList := spuImageList{}

	_spuImageList.spuImageListDo.UseDB(db, opts...)
	_spuImageList.spuImageListDo.UseModel(&model.SpuImageList{})

	tableName := _spuImageList.spuImageListDo.TableName()
	_spuImageList.ALL = field.NewAsterisk(tableName)
	_spuImageList.ImageID = field.NewInt64(tableName, "image_id")
	_spuImageList.ImageName = field.NewString(tableName, "image_name")
	_spuImageList.ImageURL = field.NewString(tableName, "image_url")
	_spuImageList.SpuID = field.NewInt64(tableName, "spu_id")
	_spuImageList.CreateTime = field.NewTime(tableName, "create_time")
	_spuImageList.UpdateTime = field.NewTime(tableName, "update_time")

	_spuImageList.fillFieldMap()

	return _spuImageList
}

type spuImageList struct {
	spuImageListDo

	ALL        field.Asterisk
	ImageID    field.Int64
	ImageName  field.String
	ImageURL   field.String
	SpuID      field.Int64
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (s spuImageList) Table(newTableName string) *spuImageList {
	s.spuImageListDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s spuImageList) As(alias string) *spuImageList {
	s.spuImageListDo.DO = *(s.spuImageListDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *spuImageList) updateTableName(table string) *spuImageList {
	s.ALL = field.NewAsterisk(table)
	s.ImageID = field.NewInt64(table, "image_id")
	s.ImageName = field.NewString(table, "image_name")
	s.ImageURL = field.NewString(table, "image_url")
	s.SpuID = field.NewInt64(table, "spu_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *spuImageList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *spuImageList) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["image_id"] = s.ImageID
	s.fieldMap["image_name"] = s.ImageName
	s.fieldMap["image_url"] = s.ImageURL
	s.fieldMap["spu_id"] = s.SpuID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s spuImageList) clone(db *gorm.DB) spuImageList {
	s.spuImageListDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s spuImageList) replaceDB(db *gorm.DB) spuImageList {
	s.spuImageListDo.ReplaceDB(db)
	return s
}

type spuImageListDo struct{ gen.DO }

type ISpuImageListDo interface {
	gen.SubQuery
	Debug() ISpuImageListDo
	WithContext(ctx context.Context) ISpuImageListDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpuImageListDo
	WriteDB() ISpuImageListDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpuImageListDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpuImageListDo
	Not(conds ...gen.Condition) ISpuImageListDo
	Or(conds ...gen.Condition) ISpuImageListDo
	Select(conds ...field.Expr) ISpuImageListDo
	Where(conds ...gen.Condition) ISpuImageListDo
	Order(conds ...field.Expr) ISpuImageListDo
	Distinct(cols ...field.Expr) ISpuImageListDo
	Omit(cols ...field.Expr) ISpuImageListDo
	Join(table schema.Tabler, on ...field.Expr) ISpuImageListDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpuImageListDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpuImageListDo
	Group(cols ...field.Expr) ISpuImageListDo
	Having(conds ...gen.Condition) ISpuImageListDo
	Limit(limit int) ISpuImageListDo
	Offset(offset int) ISpuImageListDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuImageListDo
	Unscoped() ISpuImageListDo
	Create(values ...*model.SpuImageList) error
	CreateInBatches(values []*model.SpuImageList, batchSize int) error
	Save(values ...*model.SpuImageList) error
	First() (*model.SpuImageList, error)
	Take() (*model.SpuImageList, error)
	Last() (*model.SpuImageList, error)
	Find() ([]*model.SpuImageList, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpuImageList, err error)
	FindInBatches(result *[]*model.SpuImageList, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SpuImageList) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpuImageListDo
	Assign(attrs ...field.AssignExpr) ISpuImageListDo
	Joins(fields ...field.RelationField) ISpuImageListDo
	Preload(fields ...field.RelationField) ISpuImageListDo
	FirstOrInit() (*model.SpuImageList, error)
	FirstOrCreate() (*model.SpuImageList, error)
	FindByPage(offset int, limit int) (result []*model.SpuImageList, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpuImageListDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s spuImageListDo) Debug() ISpuImageListDo {
	return s.withDO(s.DO.Debug())
}

func (s spuImageListDo) WithContext(ctx context.Context) ISpuImageListDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spuImageListDo) ReadDB() ISpuImageListDo {
	return s.Clauses(dbresolver.Read)
}

func (s spuImageListDo) WriteDB() ISpuImageListDo {
	return s.Clauses(dbresolver.Write)
}

func (s spuImageListDo) Session(config *gorm.Session) ISpuImageListDo {
	return s.withDO(s.DO.Session(config))
}

func (s spuImageListDo) Clauses(conds ...clause.Expression) ISpuImageListDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spuImageListDo) Returning(value interface{}, columns ...string) ISpuImageListDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spuImageListDo) Not(conds ...gen.Condition) ISpuImageListDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spuImageListDo) Or(conds ...gen.Condition) ISpuImageListDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spuImageListDo) Select(conds ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spuImageListDo) Where(conds ...gen.Condition) ISpuImageListDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spuImageListDo) Order(conds ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spuImageListDo) Distinct(cols ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spuImageListDo) Omit(cols ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spuImageListDo) Join(table schema.Tabler, on ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spuImageListDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spuImageListDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spuImageListDo) Group(cols ...field.Expr) ISpuImageListDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spuImageListDo) Having(conds ...gen.Condition) ISpuImageListDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spuImageListDo) Limit(limit int) ISpuImageListDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spuImageListDo) Offset(offset int) ISpuImageListDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spuImageListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuImageListDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spuImageListDo) Unscoped() ISpuImageListDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spuImageListDo) Create(values ...*model.SpuImageList) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spuImageListDo) CreateInBatches(values []*model.SpuImageList, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spuImageListDo) Save(values ...*model.SpuImageList) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spuImageListDo) First() (*model.SpuImageList, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuImageList), nil
	}
}

func (s spuImageListDo) Take() (*model.SpuImageList, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuImageList), nil
	}
}

func (s spuImageListDo) Last() (*model.SpuImageList, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuImageList), nil
	}
}

func (s spuImageListDo) Find() ([]*model.SpuImageList, error) {
	result, err := s.DO.Find()
	return result.([]*model.SpuImageList), err
}

func (s spuImageListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpuImageList, err error) {
	buf := make([]*model.SpuImageList, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spuImageListDo) FindInBatches(result *[]*model.SpuImageList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spuImageListDo) Attrs(attrs ...field.AssignExpr) ISpuImageListDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spuImageListDo) Assign(attrs ...field.AssignExpr) ISpuImageListDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spuImageListDo) Joins(fields ...field.RelationField) ISpuImageListDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spuImageListDo) Preload(fields ...field.RelationField) ISpuImageListDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spuImageListDo) FirstOrInit() (*model.SpuImageList, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuImageList), nil
	}
}

func (s spuImageListDo) FirstOrCreate() (*model.SpuImageList, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuImageList), nil
	}
}

func (s spuImageListDo) FindByPage(offset int, limit int) (result []*model.SpuImageList, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spuImageListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spuImageListDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spuImageListDo) Delete(models ...*model.SpuImageList) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spuImageListDo) withDO(do gen.Dao) *spuImageListDo {
	s.DO = *do.(*gen.DO)
	return s
}
