// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newSpuSaleAttr(db *gorm.DB, opts ...gen.DOOption) spuSaleAttr {
	_spuSaleAttr := spuSaleAttr{}

	_spuSaleAttr.spuSaleAttrDo.UseDB(db, opts...)
	_spuSaleAttr.spuSaleAttrDo.UseModel(&model.SpuSaleAttr{})

	tableName := _spuSaleAttr.spuSaleAttrDo.TableName()
	_spuSaleAttr.ALL = field.NewAsterisk(tableName)
	_spuSaleAttr.SpuSaleAttrID = field.NewInt64(tableName, "spu_sale_attr_id")
	_spuSaleAttr.BaseSaleAttrID = field.NewInt64(tableName, "base_sale_attr_id")
	_spuSaleAttr.SaleAttrName = field.NewString(tableName, "sale_attr_name")
	_spuSaleAttr.SpuID = field.NewInt64(tableName, "spu_id")
	_spuSaleAttr.CreateTime = field.NewTime(tableName, "create_time")
	_spuSaleAttr.UpdateTime = field.NewTime(tableName, "update_time")

	_spuSaleAttr.fillFieldMap()

	return _spuSaleAttr
}

type spuSaleAttr struct {
	spuSaleAttrDo

	ALL            field.Asterisk
	SpuSaleAttrID  field.Int64
	BaseSaleAttrID field.Int64
	SaleAttrName   field.String
	SpuID          field.Int64
	CreateTime     field.Time
	UpdateTime     field.Time

	fieldMap map[string]field.Expr
}

func (s spuSaleAttr) Table(newTableName string) *spuSaleAttr {
	s.spuSaleAttrDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s spuSaleAttr) As(alias string) *spuSaleAttr {
	s.spuSaleAttrDo.DO = *(s.spuSaleAttrDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *spuSaleAttr) updateTableName(table string) *spuSaleAttr {
	s.ALL = field.NewAsterisk(table)
	s.SpuSaleAttrID = field.NewInt64(table, "spu_sale_attr_id")
	s.BaseSaleAttrID = field.NewInt64(table, "base_sale_attr_id")
	s.SaleAttrName = field.NewString(table, "sale_attr_name")
	s.SpuID = field.NewInt64(table, "spu_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *spuSaleAttr) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *spuSaleAttr) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["spu_sale_attr_id"] = s.SpuSaleAttrID
	s.fieldMap["base_sale_attr_id"] = s.BaseSaleAttrID
	s.fieldMap["sale_attr_name"] = s.SaleAttrName
	s.fieldMap["spu_id"] = s.SpuID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s spuSaleAttr) clone(db *gorm.DB) spuSaleAttr {
	s.spuSaleAttrDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s spuSaleAttr) replaceDB(db *gorm.DB) spuSaleAttr {
	s.spuSaleAttrDo.ReplaceDB(db)
	return s
}

type spuSaleAttrDo struct{ gen.DO }

type ISpuSaleAttrDo interface {
	gen.SubQuery
	Debug() ISpuSaleAttrDo
	WithContext(ctx context.Context) ISpuSaleAttrDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpuSaleAttrDo
	WriteDB() ISpuSaleAttrDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpuSaleAttrDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpuSaleAttrDo
	Not(conds ...gen.Condition) ISpuSaleAttrDo
	Or(conds ...gen.Condition) ISpuSaleAttrDo
	Select(conds ...field.Expr) ISpuSaleAttrDo
	Where(conds ...gen.Condition) ISpuSaleAttrDo
	Order(conds ...field.Expr) ISpuSaleAttrDo
	Distinct(cols ...field.Expr) ISpuSaleAttrDo
	Omit(cols ...field.Expr) ISpuSaleAttrDo
	Join(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo
	Group(cols ...field.Expr) ISpuSaleAttrDo
	Having(conds ...gen.Condition) ISpuSaleAttrDo
	Limit(limit int) ISpuSaleAttrDo
	Offset(offset int) ISpuSaleAttrDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuSaleAttrDo
	Unscoped() ISpuSaleAttrDo
	Create(values ...*model.SpuSaleAttr) error
	CreateInBatches(values []*model.SpuSaleAttr, batchSize int) error
	Save(values ...*model.SpuSaleAttr) error
	First() (*model.SpuSaleAttr, error)
	Take() (*model.SpuSaleAttr, error)
	Last() (*model.SpuSaleAttr, error)
	Find() ([]*model.SpuSaleAttr, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpuSaleAttr, err error)
	FindInBatches(result *[]*model.SpuSaleAttr, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SpuSaleAttr) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpuSaleAttrDo
	Assign(attrs ...field.AssignExpr) ISpuSaleAttrDo
	Joins(fields ...field.RelationField) ISpuSaleAttrDo
	Preload(fields ...field.RelationField) ISpuSaleAttrDo
	FirstOrInit() (*model.SpuSaleAttr, error)
	FirstOrCreate() (*model.SpuSaleAttr, error)
	FindByPage(offset int, limit int) (result []*model.SpuSaleAttr, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpuSaleAttrDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s spuSaleAttrDo) Debug() ISpuSaleAttrDo {
	return s.withDO(s.DO.Debug())
}

func (s spuSaleAttrDo) WithContext(ctx context.Context) ISpuSaleAttrDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spuSaleAttrDo) ReadDB() ISpuSaleAttrDo {
	return s.Clauses(dbresolver.Read)
}

func (s spuSaleAttrDo) WriteDB() ISpuSaleAttrDo {
	return s.Clauses(dbresolver.Write)
}

func (s spuSaleAttrDo) Session(config *gorm.Session) ISpuSaleAttrDo {
	return s.withDO(s.DO.Session(config))
}

func (s spuSaleAttrDo) Clauses(conds ...clause.Expression) ISpuSaleAttrDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spuSaleAttrDo) Returning(value interface{}, columns ...string) ISpuSaleAttrDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spuSaleAttrDo) Not(conds ...gen.Condition) ISpuSaleAttrDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spuSaleAttrDo) Or(conds ...gen.Condition) ISpuSaleAttrDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spuSaleAttrDo) Select(conds ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spuSaleAttrDo) Where(conds ...gen.Condition) ISpuSaleAttrDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spuSaleAttrDo) Order(conds ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spuSaleAttrDo) Distinct(cols ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spuSaleAttrDo) Omit(cols ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spuSaleAttrDo) Join(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spuSaleAttrDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spuSaleAttrDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spuSaleAttrDo) Group(cols ...field.Expr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spuSaleAttrDo) Having(conds ...gen.Condition) ISpuSaleAttrDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spuSaleAttrDo) Limit(limit int) ISpuSaleAttrDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spuSaleAttrDo) Offset(offset int) ISpuSaleAttrDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spuSaleAttrDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpuSaleAttrDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spuSaleAttrDo) Unscoped() ISpuSaleAttrDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spuSaleAttrDo) Create(values ...*model.SpuSaleAttr) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spuSaleAttrDo) CreateInBatches(values []*model.SpuSaleAttr, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spuSaleAttrDo) Save(values ...*model.SpuSaleAttr) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spuSaleAttrDo) First() (*model.SpuSaleAttr, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuSaleAttr), nil
	}
}

func (s spuSaleAttrDo) Take() (*model.SpuSaleAttr, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuSaleAttr), nil
	}
}

func (s spuSaleAttrDo) Last() (*model.SpuSaleAttr, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuSaleAttr), nil
	}
}

func (s spuSaleAttrDo) Find() ([]*model.SpuSaleAttr, error) {
	result, err := s.DO.Find()
	return result.([]*model.SpuSaleAttr), err
}

func (s spuSaleAttrDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpuSaleAttr, err error) {
	buf := make([]*model.SpuSaleAttr, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spuSaleAttrDo) FindInBatches(result *[]*model.SpuSaleAttr, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spuSaleAttrDo) Attrs(attrs ...field.AssignExpr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spuSaleAttrDo) Assign(attrs ...field.AssignExpr) ISpuSaleAttrDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spuSaleAttrDo) Joins(fields ...field.RelationField) ISpuSaleAttrDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spuSaleAttrDo) Preload(fields ...field.RelationField) ISpuSaleAttrDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spuSaleAttrDo) FirstOrInit() (*model.SpuSaleAttr, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuSaleAttr), nil
	}
}

func (s spuSaleAttrDo) FirstOrCreate() (*model.SpuSaleAttr, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpuSaleAttr), nil
	}
}

func (s spuSaleAttrDo) FindByPage(offset int, limit int) (result []*model.SpuSaleAttr, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spuSaleAttrDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spuSaleAttrDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spuSaleAttrDo) Delete(models ...*model.SpuSaleAttr) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spuSaleAttrDo) withDO(do gen.Dao) *spuSaleAttrDo {
	s.DO = *do.(*gen.DO)
	return s
}
