// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liwook/go-vue-selection/dal/model"
)

func newTrademark(db *gorm.DB, opts ...gen.DOOption) trademark {
	_trademark := trademark{}

	_trademark.trademarkDo.UseDB(db, opts...)
	_trademark.trademarkDo.UseModel(&model.Trademark{})

	tableName := _trademark.trademarkDo.TableName()
	_trademark.ALL = field.NewAsterisk(tableName)
	_trademark.TmID = field.NewInt64(tableName, "tm_id")
	_trademark.TmName = field.NewString(tableName, "tm_name")
	_trademark.LogoURL = field.NewString(tableName, "logo_url")
	_trademark.CreateTime = field.NewTime(tableName, "create_time")
	_trademark.UpdateTime = field.NewTime(tableName, "update_time")

	_trademark.fillFieldMap()

	return _trademark
}

type trademark struct {
	trademarkDo

	ALL        field.Asterisk
	TmID       field.Int64
	TmName     field.String
	LogoURL    field.String
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (t trademark) Table(newTableName string) *trademark {
	t.trademarkDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t trademark) As(alias string) *trademark {
	t.trademarkDo.DO = *(t.trademarkDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *trademark) updateTableName(table string) *trademark {
	t.ALL = field.NewAsterisk(table)
	t.TmID = field.NewInt64(table, "tm_id")
	t.TmName = field.NewString(table, "tm_name")
	t.LogoURL = field.NewString(table, "logo_url")
	t.CreateTime = field.NewTime(table, "create_time")
	t.UpdateTime = field.NewTime(table, "update_time")

	t.fillFieldMap()

	return t
}

func (t *trademark) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *trademark) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["tm_id"] = t.TmID
	t.fieldMap["tm_name"] = t.TmName
	t.fieldMap["logo_url"] = t.LogoURL
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["update_time"] = t.UpdateTime
}

func (t trademark) clone(db *gorm.DB) trademark {
	t.trademarkDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t trademark) replaceDB(db *gorm.DB) trademark {
	t.trademarkDo.ReplaceDB(db)
	return t
}

type trademarkDo struct{ gen.DO }

type ITrademarkDo interface {
	gen.SubQuery
	Debug() ITrademarkDo
	WithContext(ctx context.Context) ITrademarkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITrademarkDo
	WriteDB() ITrademarkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITrademarkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITrademarkDo
	Not(conds ...gen.Condition) ITrademarkDo
	Or(conds ...gen.Condition) ITrademarkDo
	Select(conds ...field.Expr) ITrademarkDo
	Where(conds ...gen.Condition) ITrademarkDo
	Order(conds ...field.Expr) ITrademarkDo
	Distinct(cols ...field.Expr) ITrademarkDo
	Omit(cols ...field.Expr) ITrademarkDo
	Join(table schema.Tabler, on ...field.Expr) ITrademarkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITrademarkDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITrademarkDo
	Group(cols ...field.Expr) ITrademarkDo
	Having(conds ...gen.Condition) ITrademarkDo
	Limit(limit int) ITrademarkDo
	Offset(offset int) ITrademarkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITrademarkDo
	Unscoped() ITrademarkDo
	Create(values ...*model.Trademark) error
	CreateInBatches(values []*model.Trademark, batchSize int) error
	Save(values ...*model.Trademark) error
	First() (*model.Trademark, error)
	Take() (*model.Trademark, error)
	Last() (*model.Trademark, error)
	Find() ([]*model.Trademark, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Trademark, err error)
	FindInBatches(result *[]*model.Trademark, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Trademark) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITrademarkDo
	Assign(attrs ...field.AssignExpr) ITrademarkDo
	Joins(fields ...field.RelationField) ITrademarkDo
	Preload(fields ...field.RelationField) ITrademarkDo
	FirstOrInit() (*model.Trademark, error)
	FirstOrCreate() (*model.Trademark, error)
	FindByPage(offset int, limit int) (result []*model.Trademark, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITrademarkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t trademarkDo) Debug() ITrademarkDo {
	return t.withDO(t.DO.Debug())
}

func (t trademarkDo) WithContext(ctx context.Context) ITrademarkDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t trademarkDo) ReadDB() ITrademarkDo {
	return t.Clauses(dbresolver.Read)
}

func (t trademarkDo) WriteDB() ITrademarkDo {
	return t.Clauses(dbresolver.Write)
}

func (t trademarkDo) Session(config *gorm.Session) ITrademarkDo {
	return t.withDO(t.DO.Session(config))
}

func (t trademarkDo) Clauses(conds ...clause.Expression) ITrademarkDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t trademarkDo) Returning(value interface{}, columns ...string) ITrademarkDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t trademarkDo) Not(conds ...gen.Condition) ITrademarkDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t trademarkDo) Or(conds ...gen.Condition) ITrademarkDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t trademarkDo) Select(conds ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t trademarkDo) Where(conds ...gen.Condition) ITrademarkDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t trademarkDo) Order(conds ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t trademarkDo) Distinct(cols ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t trademarkDo) Omit(cols ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t trademarkDo) Join(table schema.Tabler, on ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t trademarkDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t trademarkDo) RightJoin(table schema.Tabler, on ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t trademarkDo) Group(cols ...field.Expr) ITrademarkDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t trademarkDo) Having(conds ...gen.Condition) ITrademarkDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t trademarkDo) Limit(limit int) ITrademarkDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t trademarkDo) Offset(offset int) ITrademarkDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t trademarkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITrademarkDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t trademarkDo) Unscoped() ITrademarkDo {
	return t.withDO(t.DO.Unscoped())
}

func (t trademarkDo) Create(values ...*model.Trademark) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t trademarkDo) CreateInBatches(values []*model.Trademark, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t trademarkDo) Save(values ...*model.Trademark) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t trademarkDo) First() (*model.Trademark, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trademark), nil
	}
}

func (t trademarkDo) Take() (*model.Trademark, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trademark), nil
	}
}

func (t trademarkDo) Last() (*model.Trademark, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trademark), nil
	}
}

func (t trademarkDo) Find() ([]*model.Trademark, error) {
	result, err := t.DO.Find()
	return result.([]*model.Trademark), err
}

func (t trademarkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Trademark, err error) {
	buf := make([]*model.Trademark, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t trademarkDo) FindInBatches(result *[]*model.Trademark, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t trademarkDo) Attrs(attrs ...field.AssignExpr) ITrademarkDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t trademarkDo) Assign(attrs ...field.AssignExpr) ITrademarkDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t trademarkDo) Joins(fields ...field.RelationField) ITrademarkDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t trademarkDo) Preload(fields ...field.RelationField) ITrademarkDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t trademarkDo) FirstOrInit() (*model.Trademark, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trademark), nil
	}
}

func (t trademarkDo) FirstOrCreate() (*model.Trademark, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trademark), nil
	}
}

func (t trademarkDo) FindByPage(offset int, limit int) (result []*model.Trademark, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t trademarkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t trademarkDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t trademarkDo) Delete(models ...*model.Trademark) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *trademarkDo) withDO(do gen.Dao) *trademarkDo {
	t.DO = *do.(*gen.DO)
	return t
}
