// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttr = "attr"

// Attr mapped from table <attr>
type Attr struct {
	AttrID     int64     `gorm:"column:attr_id;primaryKey" json:"attr_id"`
	AttrName   string    `gorm:"column:attr_name;not null" json:"attr_name"`
	CategoryID int64     `gorm:"column:category_id;not null" json:"category_id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Attr's table name
func (*Attr) TableName() string {
	return TableNameAttr
}
