// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttrValue = "attr_value"

// AttrValue mapped from table <attr_value>
type AttrValue struct {
	AttrValueID int64     `gorm:"column:attr_value_id;primaryKey" json:"attr_value_id"`
	ValueName   string    `gorm:"column:value_name;not null" json:"value_name"`
	AttrID      int64     `gorm:"column:attr_id;not null" json:"attr_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName AttrValue's table name
func (*AttrValue) TableName() string {
	return TableNameAttrValue
}
