// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory2 = "category2"

// Category2 mapped from table <category2>
type Category2 struct {
	Category2ID int64     `gorm:"column:category2_id;primaryKey" json:"category2_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Category1ID int64     `gorm:"column:category1_id;not null" json:"category1_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Category2's table name
func (*Category2) TableName() string {
	return TableNameCategory2
}
