// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory1 = "category1"

// Category1 mapped from table <category1>
type Category1 struct {
	Category1ID int64     `gorm:"column:category1_id;primaryKey" json:"category1_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Category1's table name
func (*Category1) TableName() string {
	return TableNameCategory1
}
