// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory3 = "category3"

// Category3 mapped from table <category3>
type Category3 struct {
	Category3ID int64     `gorm:"column:category3_id;primaryKey" json:"category3_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Category2ID int64     `gorm:"column:category2_id;not null" json:"category2_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Category3's table name
func (*Category3) TableName() string {
	return TableNameCategory3
}
