// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	MenuID     int64     `gorm:"column:menu_id;primaryKey" json:"menu_id"`
	Pid        *int64    `gorm:"column:pid" json:"pid"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Code       *string   `gorm:"column:code" json:"code"`
	ToCode     *string   `gorm:"column:to_code" json:"to_code"`
	Type       int32     `gorm:"column:type;not null;comment:菜单类型（1=目录，2=菜单/按钮，0=其它）" json:"type"`                      // 菜单类型（1=目录，2=菜单/按钮，0=其它）
	Status     bool      `gorm:"column:status;not null;default:true;comment:菜单状态（true=启用，false=禁用），默认启用" json:"status"` // 菜单状态（true=启用，false=禁用），默认启用
	Level      int32     `gorm:"column:level;not null;comment:菜单层级（1=一级，2=二级，3=三级，4=按钮）" json:"level"`                  // 菜单层级（1=一级，2=二级，3=三级，4=按钮）
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
