// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleMenu = "role_menu"

// RoleMenu mapped from table <role_menu>
type RoleMenu struct {
	RoleID     int64     `gorm:"column:role_id;primaryKey" json:"role_id"`
	MenuID     int64     `gorm:"column:menu_id;primaryKey" json:"menu_id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName RoleMenu's table name
func (*RoleMenu) TableName() string {
	return TableNameRoleMenu
}
