// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSaleAttr = "sale_attr"

// SaleAttr mapped from table <sale_attr>
type SaleAttr struct {
	SaleAttrID   int64     `gorm:"column:sale_attr_id;primaryKey" json:"sale_attr_id"`
	SaleAttrName string    `gorm:"column:sale_attr_name;not null" json:"sale_attr_name"`
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SaleAttr's table name
func (*SaleAttr) TableName() string {
	return TableNameSaleAttr
}
