// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSaleAttrValue = "sale_attr_value"

// SaleAttrValue mapped from table <sale_attr_value>
type SaleAttrValue struct {
	SaleAttrValueID   int64     `gorm:"column:sale_attr_value_id;primaryKey" json:"sale_attr_value_id"`
	SpuID             int64     `gorm:"column:spu_id;not null" json:"spu_id"`
	SaleAttrID        int64     `gorm:"column:sale_attr_id;not null" json:"sale_attr_id"`
	SaleAttrValueName string    `gorm:"column:sale_attr_value_name;not null" json:"sale_attr_value_name"`
	CreateTime        time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime        time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SaleAttrValue's table name
func (*SaleAttrValue) TableName() string {
	return TableNameSaleAttrValue
}
