// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSku = "sku"

// Sku mapped from table <sku>
type Sku struct {
	SkuID       int64     `gorm:"column:sku_id;primaryKey" json:"sku_id"`
	SpuID       int64     `gorm:"column:spu_id;not null" json:"spu_id"`
	Category3ID int64     `gorm:"column:category3_id;not null" json:"category3_id"`
	TmID        int64     `gorm:"column:tm_id;not null" json:"tm_id"`
	SkuName     string    `gorm:"column:sku_name;not null" json:"sku_name"`
	WeightMg    int64     `gorm:"column:weight_mg;not null;comment:重量，单位：毫克（最小重量单位，milligrams）" json:"weight_mg"` // 重量，单位：毫克（最小重量单位，milligrams）
	PriceCent   int64     `gorm:"column:price_cent;not null;comment:价格，单位：分（最小货币单位，cents）" json:"price_cent"`     // 价格，单位：分（最小货币单位，cents）
	SkuDesc     string    `gorm:"column:sku_desc;not null" json:"sku_desc"`
	IsSale      bool      `gorm:"column:is_sale;not null;comment:是否上架（true=上架，false=下架）" json:"is_sale"` // 是否上架（true=上架，false=下架）
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Sku's table name
func (*Sku) TableName() string {
	return TableNameSku
}
