// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkuAttrValue = "sku_attr_value"

// SkuAttrValue mapped from table <sku_attr_value>
type SkuAttrValue struct {
	SkuAttrValueID int64     `gorm:"column:sku_attr_value_id;primaryKey" json:"sku_attr_value_id"`
	AttrID         int64     `gorm:"column:attr_id;not null" json:"attr_id"`
	SkuID          int64     `gorm:"column:sku_id;not null" json:"sku_id"`
	AttrValueID    int64     `gorm:"column:attr_value_id;not null" json:"attr_value_id"`
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SkuAttrValue's table name
func (*SkuAttrValue) TableName() string {
	return TableNameSkuAttrValue
}
