// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkuSaleAttrValue = "sku_sale_attr_value"

// SkuSaleAttrValue mapped from table <sku_sale_attr_value>
type SkuSaleAttrValue struct {
	SkuSaleAttrValueID int64     `gorm:"column:sku_sale_attr_value_id;primaryKey" json:"sku_sale_attr_value_id"`
	SkuID              int64     `gorm:"column:sku_id;not null" json:"sku_id"`
	SaleAttrValueID    int64     `gorm:"column:sale_attr_value_id;not null" json:"sale_attr_value_id"`
	CreateTime         time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime         time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SkuSaleAttrValue's table name
func (*SkuSaleAttrValue) TableName() string {
	return TableNameSkuSaleAttrValue
}
