// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkuImage = "sku_image"

// SkuImage mapped from table <sku_image>
type SkuImage struct {
	ImageID    int64     `gorm:"column:image_id;primaryKey" json:"image_id"`
	SkuID      int64     `gorm:"column:sku_id;not null" json:"sku_id"`
	ImageURL   string    `gorm:"column:image_url;not null" json:"image_url"`
	SpuImageID *int64    `gorm:"column:spu_image_id" json:"spu_image_id"`
	IsDefault  bool      `gorm:"column:is_default;not null;comment:是否默认图片（true=默认，false=否）" json:"is_default"` // 是否默认图片（true=默认，false=否）
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SkuImage's table name
func (*SkuImage) TableName() string {
	return TableNameSkuImage
}
