// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpu = "spu"

// Spu mapped from table <spu>
type Spu struct {
	SpuID       int64     `gorm:"column:spu_id;primaryKey" json:"spu_id"`
	SpuName     string    `gorm:"column:spu_name;not null" json:"spu_name"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Category3ID int64     `gorm:"column:category3_id;not null" json:"category3_id"`
	TmID        int64     `gorm:"column:tm_id;not null" json:"tm_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Spu's table name
func (*Spu) TableName() string {
	return TableNameSpu
}
