// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpuSaleAttr = "spu_sale_attr"

// SpuSaleAttr mapped from table <spu_sale_attr>
type SpuSaleAttr struct {
	SpuSaleAttrID  int64     `gorm:"column:spu_sale_attr_id;primaryKey" json:"spu_sale_attr_id"`
	BaseSaleAttrID int64     `gorm:"column:base_sale_attr_id;not null" json:"base_sale_attr_id"`
	SaleAttrName   *string   `gorm:"column:sale_attr_name" json:"sale_attr_name"`
	SpuID          int64     `gorm:"column:spu_id;not null" json:"spu_id"`
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SpuSaleAttr's table name
func (*SpuSaleAttr) TableName() string {
	return TableNameSpuSaleAttr
}
