// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpuImageList = "spu_image_list"

// SpuImageList mapped from table <spu_image_list>
type SpuImageList struct {
	ImageID    int64     `gorm:"column:image_id;primaryKey" json:"image_id"`
	ImageName  *string   `gorm:"column:image_name" json:"image_name"`
	ImageURL   *string   `gorm:"column:image_url" json:"image_url"`
	SpuID      int64     `gorm:"column:spu_id;not null" json:"spu_id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SpuImageList's table name
func (*SpuImageList) TableName() string {
	return TableNameSpuImageList
}
