// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTrademark = "trademark"

// Trademark mapped from table <trademark>
type Trademark struct {
	TmID       int64     `gorm:"column:tm_id;primaryKey" json:"tm_id"`
	TmName     string    `gorm:"column:tm_name;not null" json:"tm_name"`
	LogoURL    *string   `gorm:"column:logo_url" json:"logo_url"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Trademark's table name
func (*Trademark) TableName() string {
	return TableNameTrademark
}
