// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID     int64     `gorm:"column:user_id;primaryKey" json:"user_id"`
	Username   string    `gorm:"column:username;not null" json:"username"`
	Password   string    `gorm:"column:password;not null" json:"password"`
	Name       *string   `gorm:"column:name" json:"name"`
	Phone      *string   `gorm:"column:phone" json:"phone"`
	Avatar     *string   `gorm:"column:avatar" json:"avatar"`
	Status     bool      `gorm:"column:status;not null;default:true;comment:账号状态（true=正常，false=禁用/锁定），默认正常" json:"status"` // 账号状态（true=正常，false=禁用/锁定），默认正常
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
