/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/acl/index/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录接口
         * @description 处理用户登录请求
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户登录参数 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamUserLogin"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/index/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登出接口
         * @description 处理用户登出
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取菜单列表
         * @description 获取菜单列表
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Menu"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增菜单接口
         * @description 处理新增菜单请求
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 菜单信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamMenuSave"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/permission/role/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 根据角色获取菜单接口
         * @description 根据角色获取菜单请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Menu"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 给角色分配权限
         * @description 给角色分配权限
         */
        post: {
            parameters: {
                query: {
                    /** @description 菜单 ID列表（逗号分隔） */
                    permissionId: string;
                };
                header?: never;
                path: {
                    /** @description 角色 ID */
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/permission/{permissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新菜单接口
         * @description 处理更新菜单请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 菜单 ID */
                    permissionId: string;
                };
                cookie?: never;
            };
            /** @description 菜单信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamMenuUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 删除菜单接口
         * @description 处理删除菜单请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 菜单 ID */
                    permissionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取角色分页列表
         * @description 获取角色列表
         */
        get: {
            parameters: {
                query: {
                    /** @description 当前页码 */
                    page: number;
                    /** @description 每页记录数 */
                    limit: number;
                    /** @description 角色名 */
                    roleName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseRoleList"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增角色接口
         * @description 处理新增角色请求
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamRoleSave"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/role/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新角色接口
         * @description 处理更新角色请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色 ID */
                    roleId: string;
                };
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamRoleUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 删除角色接口
         * @description 处理删除角色请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色 ID */
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户分页列表
         * @description 获取用户列表
         */
        get: {
            parameters: {
                query: {
                    /** @description 当前页码 */
                    page: number;
                    /** @description 每页记录数 */
                    limit: number;
                    /** @description 用户名 */
                    username?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseUserList"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        /**
         * 更新用户接口
         * @description 处理更新用户请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamUserUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        /**
         * 用户新增接口
         * @description 处理用户新增请求
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户注册信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamUserSignUp"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        /**
         * 注销当前用户接口
         * @description 删除当前登录用户自己，用户 ID 从 JWT 令牌解析
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用户信息接口
         * @description 获取用户信息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseUserInfo"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/user/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 锁定/解锁用户接口
         * @description 根据 status 锁定（false）或解锁（true）用户账号
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 锁定/解锁参数 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamUserLock"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除用户接口
         * @description 处理删除用户请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acl/user/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用户角色分配接口
         * @description 获取用户角色分配息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseToAssignRole"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 为用户分配角色
         * @description 为用户分配角色
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description 角色分配信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamDoAssignRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/attr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加或者修改已有的属性的接口
         * @description 处理添加或者修改已有的属性请求
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 属性信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.Attr"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/attr/{attrId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除基础属性接口
         * @description 处理删除基础属性请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 属性 ID */
                    attrId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/attr/{category1Id}/{category2Id}/{category3Id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取分类下已有的属性与属性值接口
         * @description 处理获取分类下已有的属性与属性值请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 分类一 ID */
                    category1Id: string;
                    /** @description 分类二 ID */
                    category2Id: string;
                    /** @description 分类三 ID */
                    category3Id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Attr"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/baseSaleAttr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有销售列表
         * @description 获取所有销售列表
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.SaleAttr"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/category1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取一级分类接口
         * @description 获取一级分类
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Category1"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/category2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增二级分类
         * @description 新增二级分类，由后端生成二级分类 ID，返回新建的分类信息
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 二级分类信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamC2Create"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Category2"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/category2/{category1Id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取二级分类接口
         * @description 获取二级分类
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 分类一 ID */
                    category1Id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Category2"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/category3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增三级分类
         * @description 新增三级分类，由后端生成三级分类 ID，返回新建的分类信息
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 三级分类信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamC3Create"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Category3"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/category3/{category2Id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取三级分类接口
         * @description 获取三级分类
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 分类二 ID */
                    category2Id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Category3"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/file/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文件接口
         * @description 上传文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description 文件
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/sku": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取SKU分页列表
         * @description 获取SKU分页列表
         */
        get: {
            parameters: {
                query: {
                    /** @description 当前页码 */
                    page: number;
                    /** @description 每页记录数 */
                    limit: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseSkuInfoList"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增SKU接口
         * @description 新增SKU接口
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description SKU信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.SkuInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/sku/{skuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取SKU详情接口
         * @description 处理获取SKU详情请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SKU ID */
                    skuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseSkuInfo"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 删除SKU接口
         * @description 处理删除SKU请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SKU ID */
                    skuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/sku/{skuId}/cancelsale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 下架SKU接口
         * @description 处理下架SKU请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SKU ID */
                    skuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/sku/{skuId}/onsale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 上架SKU接口
         * @description 处理上架SKU请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SKU ID */
                    skuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/spu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取SPU分页列表
         * @description 获取SPU分页列表
         */
        get: {
            parameters: {
                query: {
                    /** @description 当前页码 */
                    page: number;
                    /** @description 每页记录数 */
                    limit: number;
                    /** @description 三级分类 ID */
                    category3Id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseSpuList"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增SPU接口
         * @description 新增SPU接口
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["types.Spu"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/spu/{spuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新SPU接口
         * @description 更新SPU接口
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SPU ID */
                    spuId: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["types.Spu"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 删除SPU接口
         * @description 处理删除SPU请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SPU ID */
                    spuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/spu/{spuId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取商品图片列表接口
         * @description 处理获取商品图片列表请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SPU ID */
                    spuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.SpuImage"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/spu/{spuId}/saleAttr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取商品销售属性列表接口
         * @description 处理获取商品销售属性列表请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SPU ID */
                    spuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.SpuSaleAttr"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/spu/{spuId}/sku": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 根据 SPU ID 查询 SKU 接口
         * @description 处理根据 SPU ID 查询 SKU列表请求
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SPU ID */
                    spuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseSkuInfo"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/trademark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取品牌分页列表
         * @description 获取品牌列表
         */
        get: {
            parameters: {
                query: {
                    /** @description 当前页码 */
                    page: number;
                    /** @description 每页记录数 */
                    limit: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.ResponseTmList"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增品牌接口
         * @description 新增品牌接口
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 品牌信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamTmSave"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/trademark/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有品牌列表
         * @description 获取所有品牌列表
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: components["schemas"]["types.Trademark"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/trademark/{trademarkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新品牌接口
         * @description 处理更新品牌请求
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 品牌 ID */
                    trademarkId: string;
                };
                cookie?: never;
            };
            /** @description 品牌信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.ParamTmUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 删除品牌接口
         * @description 处理删除品牌请求
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 品牌 ID */
                    trademarkId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"] & {
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["result.ResponseData"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {integer} */
        "result.ResCode": 200 | 990000 | 990001 | 990002 | 990003 | 990004 | 990005 | 110000 | 110000 | 110001 | 110002 | 110003 | 110004 | 110005 | 110064 | 110065 | 110066 | 110067 | 110128 | 110129 | 110130 | 110192 | 110193 | 110194 | 110195 | 120000 | 120000 | 120064 | 120065 | 120066 | 120128 | 120129 | 120192 | 120193 | 120256 | 120257 | 120320 | 120321;
        "result.ResponseData": {
            code: components["schemas"]["result.ResCode"];
            data: unknown;
            message: string;
        };
        "types.Attr": {
            /** @description 属性ID */
            attrId?: string;
            /** @description 属性名称 */
            attrName: string;
            /** @description 属性值列表 */
            attrValueList?: components["schemas"]["types.AttrValue"][];
            /** @description 三级分类ID */
            categoryId: string;
            createTime?: string;
            updateTime?: string;
        };
        "types.AttrValue": {
            attrId?: string;
            attrValueId?: string;
            valueName: string;
        };
        "types.Category1": {
            category1Id?: string;
            createTime?: string;
            name?: string;
            updateTime?: string;
        };
        "types.Category2": {
            category1Id?: string;
            category2Id?: string;
            createTime?: string;
            name?: string;
            updateTime?: string;
        };
        "types.Category3": {
            category2Id?: string;
            category3Id?: string;
            createTime?: string;
            name?: string;
            updateTime?: string;
        };
        "types.Menu": {
            children?: components["schemas"]["types.Menu"][];
            code?: string;
            createTime?: string;
            /** @description 菜单层级：1=一级 2=二级 3=三级 4=按钮（见 MenuLevel* 常量） */
            level?: number;
            menuId?: string;
            name?: string;
            parentId?: string;
            select?: boolean;
            status?: boolean;
            toCode?: string;
            /** @description 菜单类型：1=目录 2=菜单/按钮 0=其它（见 MenuType* 常量） */
            type?: number;
            updateTime?: string;
        };
        "types.ParamC2Create": {
            category1Id: string;
            name: string;
        };
        "types.ParamC3Create": {
            category2Id: string;
            name: string;
        };
        "types.ParamDoAssignRole": {
            roleIdList?: string[];
            userId?: string;
        };
        "types.ParamMenuSave": {
            code?: string;
            /** @description 菜单层级：1=一级 2=二级 3=三级 4=按钮 */
            level?: number;
            name?: string;
            parentId?: string;
            /** @description 菜单类型：1=目录 2=菜单/按钮 0=其它 */
            type?: number;
        };
        "types.ParamMenuUpdate": {
            code?: string;
            /** @description 菜单层级：1=一级 2=二级 3=三级 4=按钮 */
            level?: number;
            menuId?: string;
            name?: string;
            parentId?: string;
        };
        "types.ParamRoleSave": {
            /** @description 角色备注 */
            remark?: string;
            /** @description 角色名称，不能为空 */
            roleName?: string;
        };
        "types.ParamRoleUpdate": {
            /** @description 角色备注 */
            remark?: string;
            /** @description 角色ID， */
            roleId?: string;
            /** @description 角色名称，不能为空 */
            roleName?: string;
        };
        "types.ParamTmSave": {
            logoUrl: string;
            tmName: string;
        };
        "types.ParamTmUpdate": {
            logoUrl: string;
            tmId?: string;
            tmName: string;
        };
        "types.ParamUserLock": {
            /** @description true=解锁（恢复正常），false=锁定（禁用） */
            status?: boolean;
            userId: string;
        };
        "types.ParamUserLogin": {
            /** @description 密码，不能为空 */
            password: string;
            /** @description 用户名，不能为空 */
            username: string;
        };
        "types.ParamUserSignUp": {
            name: string;
            password: string;
            username: string;
        };
        "types.ParamUserUpdate": {
            /** @description 头像 URL */
            avatar?: string;
            /** @description 用户昵称 */
            name?: string;
        };
        "types.ResponseRoleList": {
            current?: number;
            pages?: number;
            records?: components["schemas"]["types.Role"][];
            searchCount?: boolean;
            size?: number;
            total?: number;
        };
        "types.ResponseSkuInfo": {
            category3Id?: string;
            createTime?: string;
            isSale?: number;
            /** @description PriceCent 价格，单位：分（最小货币单位，cents）。JSON number 类型，避免浮点误差。 */
            priceCent?: number;
            skuAttrValueList?: components["schemas"]["types.SkuAttrValue"][];
            skuDesc?: string;
            skuId?: string;
            skuImageList?: components["schemas"]["types.SkuImg"][];
            skuName?: string;
            skuSaleAttrValueList?: components["schemas"]["types.SkuSaleAttrValue"][];
            spuId?: string;
            tmId?: string;
            updateTime?: string;
            /** @description WeightMg 重量，单位：毫克（最小重量单位，milligrams）。JSON number 类型，避免浮点误差。 */
            weightMg?: number;
        };
        "types.ResponseSkuInfoList": {
            current?: number;
            pages?: number;
            records?: components["schemas"]["types.ResponseSkuInfo"][];
            searchCount?: boolean;
            size?: number;
            total?: number;
        };
        "types.ResponseSpuList": {
            current?: number;
            pages?: number;
            records?: components["schemas"]["types.Spu"][];
            searchCount?: boolean;
            size?: number;
            total?: number;
        };
        "types.ResponseTmList": {
            current?: number;
            pages?: number;
            records?: components["schemas"]["types.Trademark"][];
            searchCount?: boolean;
            size?: number;
            total?: number;
        };
        "types.ResponseToAssignRole": {
            allRolesList?: components["schemas"]["types.Role"][];
            assignRoles?: components["schemas"]["types.Role"][];
        };
        "types.ResponseUser": {
            createTime?: string;
            name?: string;
            password?: string;
            phone?: string;
            roleName?: string;
            status?: boolean;
            updateTime?: string;
            userId?: string;
            username?: string;
        };
        "types.ResponseUserInfo": {
            avatar?: string;
            buttons?: string[];
            name?: string;
            roles?: string[];
            routes?: string[];
        };
        "types.ResponseUserList": {
            current?: number;
            pages?: number;
            records?: components["schemas"]["types.ResponseUser"][];
            size?: number;
            total?: number;
        };
        "types.Role": {
            createTime?: string;
            remark?: string;
            roleId?: string;
            roleName?: string;
            updateTime?: string;
        };
        "types.SaleAttr": {
            createTime?: string;
            /** @description 销售属性名称 */
            name?: string;
            /** @description 销售属性ID */
            saleAttrId?: string;
            updateTime?: string;
        };
        "types.SaleAttrValue": {
            baseSaleAttrId?: string;
            createTime?: string;
            saleAttrValueId?: string;
            saleAttrValueName?: string;
            spuId?: string;
            updateTime?: string;
        };
        "types.SkuAttrValue": {
            /** @description 平台属性ID */
            attrId?: string;
            attrName?: string;
            createTime?: string;
            skuAttrValueId?: string;
            skuId?: string;
            updateTime?: string;
            /** @description 属性值ID */
            valueId?: string;
            valueName?: string;
        };
        "types.SkuAttrValueDTO": {
            /** @description 平台属性ID */
            attrId?: string;
            attrName?: string;
            skuAttrValueId?: string;
            skuId?: string;
            /** @description 属性值ID */
            valueId?: string;
            valueName?: string;
        };
        "types.SkuImg": {
            createTime?: string;
            imgId?: string;
            imgName?: string;
            imgUrl?: string;
            isDefault?: string;
            skuId?: string;
            spuImgId?: string;
            updateTime?: string;
        };
        "types.SkuImgDTO": {
            imgId?: string;
            imgName?: string;
            imgUrl?: string;
            isDefault?: string;
            skuId?: string;
            spuImgId?: string;
        };
        "types.SkuInfo": {
            category3Id?: string;
            isSale?: number;
            /** @description PriceCent 价格，单位：分（最小货币单位，cents）。直接以“分”对外返回，避免浮点误差。 */
            priceCent?: number;
            skuAttrValueList?: components["schemas"]["types.SkuAttrValueDTO"][];
            skuDesc?: string;
            skuId?: string;
            skuImageList?: components["schemas"]["types.SkuImgDTO"][];
            skuName?: string;
            skuSaleAttrValueList?: components["schemas"]["types.SkuSaleAttrValueDTO"][];
            spuId?: string;
            tmId?: string;
            /** @description WeightMg 重量，单位：毫克（最小重量单位，milligrams）。直接以“毫克”对外返回，避免浮点误差。 */
            weightMg?: number;
        };
        "types.SkuSaleAttrValue": {
            createTime?: string;
            /** @description 销售属性ID */
            saleAttrId?: string;
            saleAttrName?: string;
            saleAttrValueId?: string;
            saleAttrValueName?: string;
            skuId?: string;
            skuSaleAttrValueId?: string;
            updateTime?: string;
        };
        "types.SkuSaleAttrValueDTO": {
            /** @description 销售属性ID */
            saleAttrId?: string;
            saleAttrName?: string;
            saleAttrValueId?: string;
            saleAttrValueName?: string;
            skuId?: string;
            skuSaleAttrValueId?: string;
        };
        "types.Spu": {
            category3Id?: string;
            createTime?: string;
            description?: string;
            spuId?: string;
            spuImageList?: components["schemas"]["types.SpuImage"][];
            spuName?: string;
            spuSaleAttrList?: components["schemas"]["types.SpuSaleAttr"][];
            tmId?: string;
            updateTime?: string;
        };
        "types.SpuImage": {
            createTime?: string;
            imgId?: string;
            imgName?: string;
            imgUrl?: string;
            spuId?: string;
            updateTime?: string;
        };
        "types.SpuSaleAttr": {
            baseSaleAttrId?: string;
            saleAttrName?: string;
            spuId?: string;
            spuSaleAttrId?: string;
            spuSaleAttrValueList?: components["schemas"]["types.SaleAttrValue"][];
        };
        "types.Trademark": {
            createTime?: string;
            logoUrl?: string;
            tmId?: string;
            tmName?: string;
            updateTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description SPU信息 */
        "types.Spu": {
            content: {
                "application/json": components["schemas"]["types.Spu"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
